Name:       network-manager-applet
Version:    1.8.22
Release:    1
Summary:    TODO
License:    GPL3
Prefix:     /usr
Source0:    %{name}-%{version}.tar.xz

%description
TODO

%prep
%setup -a 0

%build
%configure --without-selinux --disable-mobile-broadband-provider-info \
           --without-wwan --without-team
%make_build

%install    
rm -rf %{buildroot}
%make_install
rm -vf %{buildroot}%{_infodir}/dir

%files
/usr/bin/nm-applet
/usr/bin/nm-connection-editor
/usr/etc/xdg/autostart/nm-applet.desktop
/usr/include/libnma/nma-bar-code-widget.h
/usr/include/libnma/nma-bar-code.h
/usr/include/libnma/nma-cert-chooser.h
/usr/include/libnma/nma-mobile-providers.h
/usr/include/libnma/nma-mobile-wizard.h
/usr/include/libnma/nma-ui-utils.h
/usr/include/libnma/nma-version.h
/usr/include/libnma/nma-vpn-password-dialog.h
/usr/include/libnma/nma-wifi-dialog.h
/usr/lib64/girepository-1.0/NMA-1.0.typelib
/usr/lib64/libnma.a
/usr/lib64/libnma.la
/usr/lib64/libnma.so
/usr/lib64/libnma.so.0
/usr/lib64/libnma.so.0.0.0
/usr/lib64/pkgconfig/libnma.pc
/usr/share/GConf/gsettings/nm-applet.convert
/usr/share/applications/nm-applet.desktop
/usr/share/applications/nm-connection-editor.desktop
/usr/share/gir-1.0/NMA-1.0.gir
/usr/share/glib-2.0/schemas/org.gnome.nm-applet.gschema.xml
/usr/share/gtk-doc/html/libnma/NMABarCode.html
/usr/share/gtk-doc/html/libnma/NMACertChooser.html
/usr/share/gtk-doc/html/libnma/NMAMobileProvidersDatabase.html
/usr/share/gtk-doc/html/libnma/NMAMobileWizard.html
/usr/share/gtk-doc/html/libnma/NMAVpnPasswordDialog.html
/usr/share/gtk-doc/html/libnma/NMAWifiDialog.html
/usr/share/gtk-doc/html/libnma/annotation-glossary.html
/usr/share/gtk-doc/html/libnma/api-index-1.8.0.html
/usr/share/gtk-doc/html/libnma/api-index-full.html
/usr/share/gtk-doc/html/libnma/api-reference.html
/usr/share/gtk-doc/html/libnma/home.png
/usr/share/gtk-doc/html/libnma/index.html
/usr/share/gtk-doc/html/libnma/left-insensitive.png
/usr/share/gtk-doc/html/libnma/left.png
/usr/share/gtk-doc/html/libnma/libnma-nma-ui-utils.html
/usr/share/gtk-doc/html/libnma/libnma.devhelp2
/usr/share/gtk-doc/html/libnma/object-tree.html
/usr/share/gtk-doc/html/libnma/right-insensitive.png
/usr/share/gtk-doc/html/libnma/right.png
/usr/share/gtk-doc/html/libnma/style.css
/usr/share/gtk-doc/html/libnma/up-insensitive.png
/usr/share/gtk-doc/html/libnma/up.png
/usr/share/icons/hicolor/16x16/apps/nm-device-wired.png
/usr/share/icons/hicolor/16x16/apps/nm-no-connection.png
/usr/share/icons/hicolor/16x16/apps/nm-vpn-standalone-lock.png
/usr/share/icons/hicolor/22x22/apps/nm-adhoc.png
/usr/share/icons/hicolor/22x22/apps/nm-device-wired-secure.png
/usr/share/icons/hicolor/22x22/apps/nm-device-wired.png
/usr/share/icons/hicolor/22x22/apps/nm-device-wwan.png
/usr/share/icons/hicolor/22x22/apps/nm-mb-roam.png
/usr/share/icons/hicolor/22x22/apps/nm-no-connection.png
/usr/share/icons/hicolor/22x22/apps/nm-secure-lock.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-00-secure.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-00.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-100-secure.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-100.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-25-secure.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-25.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-50-secure.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-50.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-75-secure.png
/usr/share/icons/hicolor/22x22/apps/nm-signal-75.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting01.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting02.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting03.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting04.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting05.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting06.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting07.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting08.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting09.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting10.png
/usr/share/icons/hicolor/22x22/apps/nm-stage01-connecting11.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting01.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting02.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting03.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting04.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting05.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting06.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting07.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting08.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting09.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting10.png
/usr/share/icons/hicolor/22x22/apps/nm-stage02-connecting11.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting01.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting02.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting03.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting04.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting05.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting06.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting07.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting08.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting09.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting10.png
/usr/share/icons/hicolor/22x22/apps/nm-stage03-connecting11.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-3g.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-cdma-1x.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-edge.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-evdo.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-gprs.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-hspa.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-lte.png
/usr/share/icons/hicolor/22x22/apps/nm-tech-umts.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-active-lock.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting01.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting02.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting03.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting04.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting05.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting06.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting07.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting08.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting09.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting10.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting11.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting12.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting13.png
/usr/share/icons/hicolor/22x22/apps/nm-vpn-connecting14.png
/usr/share/icons/hicolor/22x22/apps/nm-wwan-tower.png
/usr/share/icons/hicolor/32x32/apps/nm-device-wired.png
/usr/share/icons/hicolor/32x32/apps/nm-no-connection.png
/usr/share/icons/hicolor/48x48/apps/nm-device-wireless.png
/usr/share/icons/hicolor/scalable/apps/nm-device-wired.svg
/usr/share/icons/hicolor/scalable/apps/nm-no-connection.svg
/usr/share/locale/af/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/an/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ar/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/as/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ast/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/be/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/be@latin/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/bg/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/bn_IN/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/bs/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ca/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ca@valencia/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/crh/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/cs/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/da/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/de/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/dz/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/el/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/en_CA/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/en_GB/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/eo/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/es/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/et/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/eu/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/fa/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/fi/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/fr/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/gd/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/gl/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/gu/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/he/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/hi/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/hr/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/hu/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/id/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/is/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/it/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ja/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/kk/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/km/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/kn/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ko/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ku/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/lt/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/lv/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/mk/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ml/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/mr/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ms/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/nb/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ne/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/nl/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/nn/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/oc/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/or/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/pa/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/pl/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/pt/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/pt_BR/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ro/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ru/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/rw/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/sk/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/sl/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/sq/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/sr/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/sr@latin/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/sv/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ta/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/te/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/tg/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/th/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/tr/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ug/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/uk/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/ur/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/vi/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/wa/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/zh_CN/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/zh_HK/LC_MESSAGES/network-manager-applet.mo
/usr/share/locale/zh_TW/LC_MESSAGES/network-manager-applet.mo
/usr/share/man/man1/nm-applet.1.gz
/usr/share/man/man1/nm-connection-editor.1.gz
/usr/share/metainfo/nm-connection-editor.appdata.xml

%changelog
# let's skip this for now

