#!/bin/env python3

import argparse
import logging
import sys
sys.path.append("./builder/")

import db
from build import PackageBuilder

logging.basicConfig(level=logging.DEBUG)

parser = argparse.ArgumentParser(description='Build System')

# Subparsers
command_parsers = parser.add_subparsers(dest='command')
build_parser = command_parsers.add_parser('build')
query_parser = command_parsers.add_parser('query')

# build
build_parser.add_argument("package_name")
#build_parser.add_argument("--all", action="store_true")

# query
query_parser.add_argument("mode")
args = parser.parse_args()

pbuilder = PackageBuilder()

if args.command == "query":
    if args.mode == "failed":
        package_db = db.PackageDatabase()
        failed_packages = package_db.get_failed()
        for p in failed_packages:
            print(p[1])

if args.command == "build":
    if args.package_name == "all":
        pbuilder.build_all()
    else:
        pbuilder.build_package(args.package_name)


#print(args)