Name:       gettext
Version:    0.19.8.1
Release:    1
Summary:    TODO
License:    GPL3
Source0:    %{name}-%{version}.tar.xz
Prefix:     /usr

%description
TODO

%prep
%setup -q -a0

%build
sed -i '/^TESTS =/d' gettext-runtime/tests/Makefile.in &&
sed -i 's/test-lock..EXEEXT.//' gettext-tools/gnulib-tests/Makefile.in
sed -e '/AppData/{N;N;p;s/\.appdata\./.metainfo./}' \
    -i gettext-tools/its/appdata.loc

%configure --disable-static \
           --docdir=/usr/share/doc/gettext-0.19.8.1
%make_build

%install
rm -rf %{buildroot}
%make_install
rm -vf %{buildroot}%{_infodir}/dir*
chmod -v 0755 %{buildroot}/usr/lib64/preloadable_libintl.so
rm -rf %{buildroot}/usr/share/doc/gettext-0.19.8.1/examples

%files
/usr/bin/autopoint
/usr/bin/envsubst
/usr/bin/gettext
/usr/bin/gettext.sh
/usr/bin/gettextize
/usr/bin/msgattrib
/usr/bin/msgcat
/usr/bin/msgcmp
/usr/bin/msgcomm
/usr/bin/msgconv
/usr/bin/msgen
/usr/bin/msgexec
/usr/bin/msgfilter
/usr/bin/msgfmt
/usr/bin/msggrep
/usr/bin/msginit
/usr/bin/msgmerge
/usr/bin/msgunfmt
/usr/bin/msguniq
/usr/bin/ngettext
/usr/bin/recode-sr-latin
/usr/bin/xgettext
/usr/include/autosprintf.h
/usr/include/gettext-po.h
/usr/lib64/gettext/cldr-plurals
/usr/lib64/gettext/hostname
/usr/lib64/gettext/project-id
/usr/lib64/gettext/urlget
/usr/lib64/gettext/user-email
/usr/lib64/libasprintf.la
/usr/lib64/libasprintf.so
/usr/lib64/libasprintf.so.0
/usr/lib64/libasprintf.so.0.0.0
/usr/lib64/libgettextlib-0.19.8.1.so
/usr/lib64/libgettextlib.la
/usr/lib64/libgettextlib.so
/usr/lib64/libgettextpo.la
/usr/lib64/libgettextpo.so
/usr/lib64/libgettextpo.so.0
/usr/lib64/libgettextpo.so.0.5.4
/usr/lib64/libgettextsrc-0.19.8.1.so
/usr/lib64/libgettextsrc.la
/usr/lib64/libgettextsrc.so
/usr/lib64/preloadable_libintl.so
/usr/share/aclocal/codeset.m4
/usr/share/aclocal/extern-inline.m4
/usr/share/aclocal/fcntl-o.m4
/usr/share/aclocal/gettext.m4
/usr/share/aclocal/glibc2.m4
/usr/share/aclocal/glibc21.m4
/usr/share/aclocal/iconv.m4
/usr/share/aclocal/intdiv0.m4
/usr/share/aclocal/intl.m4
/usr/share/aclocal/intldir.m4
/usr/share/aclocal/intlmacosx.m4
/usr/share/aclocal/intmax.m4
/usr/share/aclocal/inttypes-pri.m4
/usr/share/aclocal/inttypes_h.m4
/usr/share/aclocal/lcmessage.m4
/usr/share/aclocal/lib-ld.m4
/usr/share/aclocal/lib-link.m4
/usr/share/aclocal/lib-prefix.m4
/usr/share/aclocal/lock.m4
/usr/share/aclocal/longlong.m4
/usr/share/aclocal/nls.m4
/usr/share/aclocal/po.m4
/usr/share/aclocal/printf-posix.m4
/usr/share/aclocal/progtest.m4
/usr/share/aclocal/size_max.m4
/usr/share/aclocal/stdint_h.m4
/usr/share/aclocal/threadlib.m4
/usr/share/aclocal/uintmax_t.m4
/usr/share/aclocal/visibility.m4
/usr/share/aclocal/wchar_t.m4
/usr/share/aclocal/wint_t.m4
/usr/share/aclocal/xsize.m4
/usr/share/doc/gettext-0.19.8.1/FAQ.html
/usr/share/doc/gettext-0.19.8.1/autopoint.1.html
/usr/share/doc/gettext-0.19.8.1/autosprintf_all.html
/usr/share/doc/gettext-0.19.8.1/bind_textdomain_codeset.3.html
/usr/share/doc/gettext-0.19.8.1/bindtextdomain.3.html
/usr/share/doc/gettext-0.19.8.1/csharpdoc/GNU_Gettext.html
/usr/share/doc/gettext-0.19.8.1/csharpdoc/GNU_Gettext_GettextResourceManager.html
/usr/share/doc/gettext-0.19.8.1/csharpdoc/GNU_Gettext_GettextResourceSet.html
/usr/share/doc/gettext-0.19.8.1/csharpdoc/begin.html
/usr/share/doc/gettext-0.19.8.1/csharpdoc/index.html
/usr/share/doc/gettext-0.19.8.1/csharpdoc/namespaces.html
/usr/share/doc/gettext-0.19.8.1/envsubst.1.html
/usr/share/doc/gettext-0.19.8.1/gettext.1.html
/usr/share/doc/gettext-0.19.8.1/gettext.3.html
/usr/share/doc/gettext-0.19.8.1/gettext_1.html
/usr/share/doc/gettext-0.19.8.1/gettext_10.html
/usr/share/doc/gettext-0.19.8.1/gettext_11.html
/usr/share/doc/gettext-0.19.8.1/gettext_12.html
/usr/share/doc/gettext-0.19.8.1/gettext_13.html
/usr/share/doc/gettext-0.19.8.1/gettext_14.html
/usr/share/doc/gettext-0.19.8.1/gettext_15.html
/usr/share/doc/gettext-0.19.8.1/gettext_16.html
/usr/share/doc/gettext-0.19.8.1/gettext_17.html
/usr/share/doc/gettext-0.19.8.1/gettext_18.html
/usr/share/doc/gettext-0.19.8.1/gettext_19.html
/usr/share/doc/gettext-0.19.8.1/gettext_2.html
/usr/share/doc/gettext-0.19.8.1/gettext_20.html
/usr/share/doc/gettext-0.19.8.1/gettext_21.html
/usr/share/doc/gettext-0.19.8.1/gettext_22.html
/usr/share/doc/gettext-0.19.8.1/gettext_23.html
/usr/share/doc/gettext-0.19.8.1/gettext_24.html
/usr/share/doc/gettext-0.19.8.1/gettext_25.html
/usr/share/doc/gettext-0.19.8.1/gettext_3.html
/usr/share/doc/gettext-0.19.8.1/gettext_4.html
/usr/share/doc/gettext-0.19.8.1/gettext_5.html
/usr/share/doc/gettext-0.19.8.1/gettext_6.html
/usr/share/doc/gettext-0.19.8.1/gettext_7.html
/usr/share/doc/gettext-0.19.8.1/gettext_8.html
/usr/share/doc/gettext-0.19.8.1/gettext_9.html
/usr/share/doc/gettext-0.19.8.1/gettext_foot.html
/usr/share/doc/gettext-0.19.8.1/gettext_toc.html
/usr/share/doc/gettext-0.19.8.1/gettextize.1.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/allclasses-frame.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/deprecated-list.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/gnu/gettext/GettextResource.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/gnu/gettext/package-frame.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/gnu/gettext/package-summary.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/gnu/gettext/package-tree.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/help-doc.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/index-all.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/index.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/overview-tree.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/package-list
/usr/share/doc/gettext-0.19.8.1/javadoc2/packages.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/serialized-form.html
/usr/share/doc/gettext-0.19.8.1/javadoc2/stylesheet.css
/usr/share/doc/gettext-0.19.8.1/msgattrib.1.html
/usr/share/doc/gettext-0.19.8.1/msgcat.1.html
/usr/share/doc/gettext-0.19.8.1/msgcmp.1.html
/usr/share/doc/gettext-0.19.8.1/msgcomm.1.html
/usr/share/doc/gettext-0.19.8.1/msgconv.1.html
/usr/share/doc/gettext-0.19.8.1/msgen.1.html
/usr/share/doc/gettext-0.19.8.1/msgexec.1.html
/usr/share/doc/gettext-0.19.8.1/msgfilter.1.html
/usr/share/doc/gettext-0.19.8.1/msgfmt.1.html
/usr/share/doc/gettext-0.19.8.1/msggrep.1.html
/usr/share/doc/gettext-0.19.8.1/msginit.1.html
/usr/share/doc/gettext-0.19.8.1/msgmerge.1.html
/usr/share/doc/gettext-0.19.8.1/msgunfmt.1.html
/usr/share/doc/gettext-0.19.8.1/msguniq.1.html
/usr/share/doc/gettext-0.19.8.1/ngettext.1.html
/usr/share/doc/gettext-0.19.8.1/ngettext.3.html
/usr/share/doc/gettext-0.19.8.1/recode-sr-latin.1.html
/usr/share/doc/gettext-0.19.8.1/textdomain.3.html
/usr/share/doc/gettext-0.19.8.1/tutorial.html
/usr/share/doc/gettext-0.19.8.1/xgettext.1.html
/usr/share/gettext-0.19.8/its/appdata.its
/usr/share/gettext-0.19.8/its/appdata.loc
/usr/share/gettext-0.19.8/its/glade.loc
/usr/share/gettext-0.19.8/its/glade1.its
/usr/share/gettext-0.19.8/its/glade2.its
/usr/share/gettext-0.19.8/its/gsettings.its
/usr/share/gettext-0.19.8/its/gsettings.loc
/usr/share/gettext-0.19.8/its/gtkbuilder.its
/usr/share/gettext/ABOUT-NLS
/usr/share/gettext/archive.dir.tar.xz
/usr/share/gettext/config.rpath
/usr/share/gettext/gettext.h
/usr/share/gettext/intl/COPYING.LIB
/usr/share/gettext/intl/Makefile.in
/usr/share/gettext/intl/VERSION
/usr/share/gettext/intl/bindtextdom.c
/usr/share/gettext/intl/config.charset
/usr/share/gettext/intl/dcgettext.c
/usr/share/gettext/intl/dcigettext.c
/usr/share/gettext/intl/dcngettext.c
/usr/share/gettext/intl/dgettext.c
/usr/share/gettext/intl/dngettext.c
/usr/share/gettext/intl/eval-plural.h
/usr/share/gettext/intl/explodename.c
/usr/share/gettext/intl/export.h
/usr/share/gettext/intl/finddomain.c
/usr/share/gettext/intl/gettext.c
/usr/share/gettext/intl/gettextP.h
/usr/share/gettext/intl/gmo.h
/usr/share/gettext/intl/hash-string.c
/usr/share/gettext/intl/hash-string.h
/usr/share/gettext/intl/intl-compat.c
/usr/share/gettext/intl/intl-exports.c
/usr/share/gettext/intl/l10nflist.c
/usr/share/gettext/intl/langprefs.c
/usr/share/gettext/intl/libgnuintl.in.h
/usr/share/gettext/intl/libintl.rc
/usr/share/gettext/intl/loadinfo.h
/usr/share/gettext/intl/loadmsgcat.c
/usr/share/gettext/intl/localcharset.c
/usr/share/gettext/intl/localcharset.h
/usr/share/gettext/intl/locale.alias
/usr/share/gettext/intl/localealias.c
/usr/share/gettext/intl/localename.c
/usr/share/gettext/intl/lock.c
/usr/share/gettext/intl/lock.h
/usr/share/gettext/intl/log.c
/usr/share/gettext/intl/ngettext.c
/usr/share/gettext/intl/os2compat.c
/usr/share/gettext/intl/os2compat.h
/usr/share/gettext/intl/osdep.c
/usr/share/gettext/intl/plural-exp.c
/usr/share/gettext/intl/plural-exp.h
/usr/share/gettext/intl/plural.c
/usr/share/gettext/intl/plural.y
/usr/share/gettext/intl/printf-args.c
/usr/share/gettext/intl/printf-args.h
/usr/share/gettext/intl/printf-parse.c
/usr/share/gettext/intl/printf-parse.h
/usr/share/gettext/intl/printf.c
/usr/share/gettext/intl/ref-add.sin
/usr/share/gettext/intl/ref-del.sin
/usr/share/gettext/intl/relocatable.c
/usr/share/gettext/intl/relocatable.h
/usr/share/gettext/intl/setlocale.c
/usr/share/gettext/intl/textdomain.c
/usr/share/gettext/intl/threadlib.c
/usr/share/gettext/intl/tsearch.c
/usr/share/gettext/intl/tsearch.h
/usr/share/gettext/intl/vasnprintf.c
/usr/share/gettext/intl/vasnprintf.h
/usr/share/gettext/intl/vasnwprintf.h
/usr/share/gettext/intl/verify.h
/usr/share/gettext/intl/version.c
/usr/share/gettext/intl/wprintf-parse.h
/usr/share/gettext/intl/xsize.c
/usr/share/gettext/intl/xsize.h
/usr/share/gettext/javaversion.class
/usr/share/gettext/msgunfmt.tcl
/usr/share/gettext/po/Makefile.in.in
/usr/share/gettext/po/Makevars.template
/usr/share/gettext/po/Rules-quot
/usr/share/gettext/po/boldquot.sed
/usr/share/gettext/po/en@boldquot.header
/usr/share/gettext/po/en@quot.header
/usr/share/gettext/po/insert-header.sin
/usr/share/gettext/po/quot.sed
/usr/share/gettext/po/remove-potcdate.sin
/usr/share/gettext/projects/GNOME/team-address
/usr/share/gettext/projects/GNOME/teams.html
/usr/share/gettext/projects/GNOME/teams.url
/usr/share/gettext/projects/GNOME/trigger
/usr/share/gettext/projects/KDE/team-address
/usr/share/gettext/projects/KDE/teams.html
/usr/share/gettext/projects/KDE/teams.url
/usr/share/gettext/projects/KDE/trigger
/usr/share/gettext/projects/TP/team-address
/usr/share/gettext/projects/TP/teams.html
/usr/share/gettext/projects/TP/teams.url
/usr/share/gettext/projects/TP/trigger
/usr/share/gettext/projects/index
/usr/share/gettext/projects/team-address
/usr/share/gettext/styles/po-default.css
/usr/share/gettext/styles/po-emacs-x.css
/usr/share/gettext/styles/po-emacs-xterm.css
/usr/share/gettext/styles/po-emacs-xterm16.css
/usr/share/gettext/styles/po-emacs-xterm256.css
/usr/share/gettext/styles/po-vim.css
/usr/share/info/autosprintf.info.gz
/usr/share/info/gettext.info.gz
/usr/share/locale/be/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/be/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/bg/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/bg/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/ca/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/ca/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/cs/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/cs/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/da/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/da/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/de/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/de/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/el/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/el/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/en@boldquot/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/en@boldquot/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/en@quot/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/en@quot/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/eo/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/es/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/es/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/et/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/et/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/eu/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/fi/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/fi/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/fr/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/fr/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/ga/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/gl/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/gl/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/hr/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/hu/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/id/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/id/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/it/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/it/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/ja/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/ja/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/ko/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/ko/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/nb/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/nb/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/nl/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/nl/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/nn/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/nn/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/pa/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/pl/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/pl/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/pt/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/pt/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/pt_BR/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/pt_BR/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/ro/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/ro/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/ru/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/ru/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/sk/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/sk/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/sl/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/sl/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/sr/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/sr/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/sv/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/sv/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/tr/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/tr/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/uk/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/uk/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/vi/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/vi/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/zh_CN/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/zh_CN/LC_MESSAGES/gettext-tools.mo
/usr/share/locale/zh_HK/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/zh_TW/LC_MESSAGES/gettext-runtime.mo
/usr/share/locale/zh_TW/LC_MESSAGES/gettext-tools.mo
/usr/share/man/man1/autopoint.1.gz
/usr/share/man/man1/envsubst.1.gz
/usr/share/man/man1/gettext.1.gz
/usr/share/man/man1/gettextize.1.gz
/usr/share/man/man1/msgattrib.1.gz
/usr/share/man/man1/msgcat.1.gz
/usr/share/man/man1/msgcmp.1.gz
/usr/share/man/man1/msgcomm.1.gz
/usr/share/man/man1/msgconv.1.gz
/usr/share/man/man1/msgen.1.gz
/usr/share/man/man1/msgexec.1.gz
/usr/share/man/man1/msgfilter.1.gz
/usr/share/man/man1/msgfmt.1.gz
/usr/share/man/man1/msggrep.1.gz
/usr/share/man/man1/msginit.1.gz
/usr/share/man/man1/msgmerge.1.gz
/usr/share/man/man1/msgunfmt.1.gz
/usr/share/man/man1/msguniq.1.gz
/usr/share/man/man1/ngettext.1.gz
/usr/share/man/man1/recode-sr-latin.1.gz
/usr/share/man/man1/xgettext.1.gz
/usr/share/man/man3/bind_textdomain_codeset.3.gz
/usr/share/man/man3/bindtextdomain.3.gz
/usr/share/man/man3/dcgettext.3.gz
/usr/share/man/man3/dcngettext.3.gz
/usr/share/man/man3/dgettext.3.gz
/usr/share/man/man3/dngettext.3.gz
/usr/share/man/man3/gettext.3.gz
/usr/share/man/man3/ngettext.3.gz
/usr/share/man/man3/textdomain.3.gz


%changelog
# let's skip this for now
