Name:       pulseaudio
Version:    12.2
Release:    1
Summary:    TODO
License:    GPL3
Prefix:     /usr
Source0:    %{name}-%{version}.tar.xz


%description
TODO

%prep
%setup -a 0 

%build
%configure  --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-bluez4     \
            --disable-bluez5     \
            --disable-rpath
%make_build

%install    
rm -rf %{buildroot}
%make_install
rm -vf %{buildroot}%{_infodir}/dir*
sed -i '/load-module module-console-kit/s/^/#/' %{buildroot}/etc/pulse/default.pa
rm -fv %{buildroot}/etc/dbus-1/system.d/pulseaudio-system.conf

%files
/etc/pulse/client.conf
/etc/pulse/daemon.conf
/etc/pulse/default.pa
/etc/pulse/system.pa
/etc/xdg/autostart/pulseaudio.desktop
/usr/bin/esdcompat
/usr/bin/pacat
/usr/bin/pacmd
/usr/bin/pactl
/usr/bin/padsp
/usr/bin/pamon
/usr/bin/paplay
/usr/bin/parec
/usr/bin/parecord
/usr/bin/pasuspender
/usr/bin/pax11publish
/usr/bin/pulseaudio
/usr/bin/start-pulseaudio-x11
/usr/include/pulse/cdecl.h
/usr/include/pulse/channelmap.h
/usr/include/pulse/context.h
/usr/include/pulse/def.h
/usr/include/pulse/direction.h
/usr/include/pulse/error.h
/usr/include/pulse/ext-device-manager.h
/usr/include/pulse/ext-device-restore.h
/usr/include/pulse/ext-stream-restore.h
/usr/include/pulse/format.h
/usr/include/pulse/gccmacro.h
/usr/include/pulse/glib-mainloop.h
/usr/include/pulse/introspect.h
/usr/include/pulse/mainloop-api.h
/usr/include/pulse/mainloop-signal.h
/usr/include/pulse/mainloop.h
/usr/include/pulse/operation.h
/usr/include/pulse/proplist.h
/usr/include/pulse/pulseaudio.h
/usr/include/pulse/rtclock.h
/usr/include/pulse/sample.h
/usr/include/pulse/scache.h
/usr/include/pulse/simple.h
/usr/include/pulse/stream.h
/usr/include/pulse/subscribe.h
/usr/include/pulse/thread-mainloop.h
/usr/include/pulse/timeval.h
/usr/include/pulse/utf8.h
/usr/include/pulse/util.h
/usr/include/pulse/version.h
/usr/include/pulse/volume.h
/usr/include/pulse/xmalloc.h
/usr/lib64/cmake/PulseAudio/PulseAudioConfig.cmake
/usr/lib64/cmake/PulseAudio/PulseAudioConfigVersion.cmake
/usr/lib64/libpulse-mainloop-glib.la
/usr/lib64/libpulse-mainloop-glib.so
/usr/lib64/libpulse-mainloop-glib.so.0
/usr/lib64/libpulse-mainloop-glib.so.0.0.5
/usr/lib64/libpulse-simple.la
/usr/lib64/libpulse-simple.so
/usr/lib64/libpulse-simple.so.0
/usr/lib64/libpulse-simple.so.0.1.1
/usr/lib64/libpulse.la
/usr/lib64/libpulse.so
/usr/lib64/libpulse.so.0
/usr/lib64/libpulse.so.0.20.3
/usr/lib64/pkgconfig/libpulse-mainloop-glib.pc
/usr/lib64/pkgconfig/libpulse-simple.pc
/usr/lib64/pkgconfig/libpulse.pc
/usr/lib64/pulse-12.2/modules/libcli.so
/usr/lib64/pulse-12.2/modules/liboss-util.so
/usr/lib64/pulse-12.2/modules/libprotocol-cli.so
/usr/lib64/pulse-12.2/modules/libprotocol-esound.so
/usr/lib64/pulse-12.2/modules/libprotocol-http.so
/usr/lib64/pulse-12.2/modules/libprotocol-native.so
/usr/lib64/pulse-12.2/modules/libprotocol-simple.so
/usr/lib64/pulse-12.2/modules/libraop.so
/usr/lib64/pulse-12.2/modules/librtp.so
/usr/lib64/pulse-12.2/modules/module-allow-passthrough.so
/usr/lib64/pulse-12.2/modules/module-always-sink.so
/usr/lib64/pulse-12.2/modules/module-always-source.so
/usr/lib64/pulse-12.2/modules/module-augment-properties.so
/usr/lib64/pulse-12.2/modules/module-card-restore.so
/usr/lib64/pulse-12.2/modules/module-cli-protocol-tcp.so
/usr/lib64/pulse-12.2/modules/module-cli-protocol-unix.so
/usr/lib64/pulse-12.2/modules/module-cli.so
/usr/lib64/pulse-12.2/modules/module-combine-sink.so
/usr/lib64/pulse-12.2/modules/module-combine.so
/usr/lib64/pulse-12.2/modules/module-console-kit.so
/usr/lib64/pulse-12.2/modules/module-dbus-protocol.so
/usr/lib64/pulse-12.2/modules/module-default-device-restore.so
/usr/lib64/pulse-12.2/modules/module-detect.so
/usr/lib64/pulse-12.2/modules/module-device-manager.so
/usr/lib64/pulse-12.2/modules/module-device-restore.so
/usr/lib64/pulse-12.2/modules/module-echo-cancel.so
/usr/lib64/pulse-12.2/modules/module-esound-compat-spawnfd.so
/usr/lib64/pulse-12.2/modules/module-esound-compat-spawnpid.so
/usr/lib64/pulse-12.2/modules/module-esound-protocol-tcp.so
/usr/lib64/pulse-12.2/modules/module-esound-protocol-unix.so
/usr/lib64/pulse-12.2/modules/module-esound-sink.so
/usr/lib64/pulse-12.2/modules/module-filter-apply.so
/usr/lib64/pulse-12.2/modules/module-filter-heuristics.so
/usr/lib64/pulse-12.2/modules/module-gsettings.so
/usr/lib64/pulse-12.2/modules/module-hal-detect.so
/usr/lib64/pulse-12.2/modules/module-http-protocol-tcp.so
/usr/lib64/pulse-12.2/modules/module-http-protocol-unix.so
/usr/lib64/pulse-12.2/modules/module-intended-roles.so
/usr/lib64/pulse-12.2/modules/module-ladspa-sink.so
/usr/lib64/pulse-12.2/modules/module-loopback.so
/usr/lib64/pulse-12.2/modules/module-match.so
/usr/lib64/pulse-12.2/modules/module-mmkbd-evdev.so
/usr/lib64/pulse-12.2/modules/module-native-protocol-fd.so
/usr/lib64/pulse-12.2/modules/module-native-protocol-tcp.so
/usr/lib64/pulse-12.2/modules/module-native-protocol-unix.so
/usr/lib64/pulse-12.2/modules/module-null-sink.so
/usr/lib64/pulse-12.2/modules/module-null-source.so
/usr/lib64/pulse-12.2/modules/module-oss.so
/usr/lib64/pulse-12.2/modules/module-pipe-sink.so
/usr/lib64/pulse-12.2/modules/module-pipe-source.so
/usr/lib64/pulse-12.2/modules/module-position-event-sounds.so
/usr/lib64/pulse-12.2/modules/module-raop-sink.so
/usr/lib64/pulse-12.2/modules/module-remap-sink.so
/usr/lib64/pulse-12.2/modules/module-remap-source.so
/usr/lib64/pulse-12.2/modules/module-rescue-streams.so
/usr/lib64/pulse-12.2/modules/module-role-cork.so
/usr/lib64/pulse-12.2/modules/module-role-ducking.so
/usr/lib64/pulse-12.2/modules/module-rtp-recv.so
/usr/lib64/pulse-12.2/modules/module-rtp-send.so
/usr/lib64/pulse-12.2/modules/module-rygel-media-server.so
/usr/lib64/pulse-12.2/modules/module-simple-protocol-tcp.so
/usr/lib64/pulse-12.2/modules/module-simple-protocol-unix.so
/usr/lib64/pulse-12.2/modules/module-sine-source.so
/usr/lib64/pulse-12.2/modules/module-sine.so
/usr/lib64/pulse-12.2/modules/module-stream-restore.so
/usr/lib64/pulse-12.2/modules/module-suspend-on-idle.so
/usr/lib64/pulse-12.2/modules/module-switch-on-connect.so
/usr/lib64/pulse-12.2/modules/module-switch-on-port-available.so
/usr/lib64/pulse-12.2/modules/module-tunnel-sink-new.so
/usr/lib64/pulse-12.2/modules/module-tunnel-sink.so
/usr/lib64/pulse-12.2/modules/module-tunnel-source-new.so
/usr/lib64/pulse-12.2/modules/module-tunnel-source.so
/usr/lib64/pulse-12.2/modules/module-udev-detect.so
/usr/lib64/pulse-12.2/modules/module-virtual-sink.so
/usr/lib64/pulse-12.2/modules/module-virtual-source.so
/usr/lib64/pulse-12.2/modules/module-virtual-surround-sink.so
/usr/lib64/pulse-12.2/modules/module-volume-restore.so
/usr/lib64/pulse-12.2/modules/module-x11-bell.so
/usr/lib64/pulse-12.2/modules/module-x11-cork-request.so
/usr/lib64/pulse-12.2/modules/module-x11-publish.so
/usr/lib64/pulse-12.2/modules/module-x11-xsmp.so
/usr/lib64/pulseaudio/libpulsecommon-12.2.la
/usr/lib64/pulseaudio/libpulsecommon-12.2.so
/usr/lib64/pulseaudio/libpulsecore-12.2.la
/usr/lib64/pulseaudio/libpulsecore-12.2.so
/usr/lib64/pulseaudio/libpulsedsp.la
/usr/lib64/pulseaudio/libpulsedsp.so
/usr/libexec/pulse/gsettings-helper
/usr/share/GConf/gsettings/pulseaudio.convert
/usr/share/bash-completion/completions/pacat
/usr/share/bash-completion/completions/pacmd
/usr/share/bash-completion/completions/pactl
/usr/share/bash-completion/completions/padsp
/usr/share/bash-completion/completions/paplay
/usr/share/bash-completion/completions/parec
/usr/share/bash-completion/completions/parecord
/usr/share/bash-completion/completions/pasuspender
/usr/share/bash-completion/completions/pulseaudio
/usr/share/glib-2.0/schemas/org.freedesktop.pulseaudio.gschema.xml
/usr/share/locale/as/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/be/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/bn_IN/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/ca/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/cs/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/de/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/de_CH/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/el/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/es/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/fi/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/fr/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/gl/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/gu/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/he/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/hi/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/hr/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/hu/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/id/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/it/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/ja/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/kn/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/ko/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/lt/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/ml/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/mr/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/nl/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/nn/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/oc/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/or/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/pa/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/pl/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/pt/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/pt_BR/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/ru/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/sk/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/sr/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/sr@latin/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/sv/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/ta/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/te/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/tr/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/uk/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/zh_CN/LC_MESSAGES/pulseaudio.mo
/usr/share/locale/zh_TW/LC_MESSAGES/pulseaudio.mo
/usr/share/man/man1/esdcompat.1.gz
/usr/share/man/man1/pacat.1.gz
/usr/share/man/man1/pacmd.1.gz
/usr/share/man/man1/pactl.1.gz
/usr/share/man/man1/padsp.1.gz
/usr/share/man/man1/pamon.1.gz
/usr/share/man/man1/paplay.1.gz
/usr/share/man/man1/parec.1.gz
/usr/share/man/man1/parecord.1.gz
/usr/share/man/man1/pasuspender.1.gz
/usr/share/man/man1/pax11publish.1.gz
/usr/share/man/man1/pulseaudio.1.gz
/usr/share/man/man1/start-pulseaudio-x11.1.gz
/usr/share/man/man5/default.pa.5.gz
/usr/share/man/man5/pulse-cli-syntax.5.gz
/usr/share/man/man5/pulse-client.conf.5.gz
/usr/share/man/man5/pulse-daemon.conf.5.gz
/usr/share/vala/vapi/libpulse-mainloop-glib.deps
/usr/share/vala/vapi/libpulse-mainloop-glib.vapi
/usr/share/vala/vapi/libpulse-simple.deps
/usr/share/vala/vapi/libpulse-simple.vapi
/usr/share/vala/vapi/libpulse.deps
/usr/share/vala/vapi/libpulse.vapi
/usr/share/zsh/site-functions/_pulseaudio


%changelog
# let's skip this for now

