Name:       shadow
Version:    4.6
Release:    1
Summary:    TODO
License:    GPL3
Source0:    %{name}-%{version}.tar.xz
Prefix:     /usr

%description
TODO Commands to enable shadowed passwords etc
see: http://www.linuxfromscratch.org/lfs/view/stable/chapter06/shadow.html

%prep
%setup -q -a0

%build
sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs
sed -i 's/1000/999/' etc/useradd
%configure --sysconfdir=/etc --with-group-name-max-length=32
%make_build

%install
rm -rf %{buildroot}
%make_install
rm -vf %{buildroot}%{_infodir}/dir*

mkdir -pv %{buildroot}/etc

cat > %{buildroot}/etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
daemon:x:6:6:Daemon User:/dev/null:/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/var/run/dbus:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
EOF

cat > %{buildroot}/etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
input:x:24:
mail:x:34:
kvm:x:61:
wheel:x:97:
nogroup:x:99:
users:x:999:
EOF


%files
/etc/group
/etc/passwd
/etc/default/useradd
/etc/limits
/etc/login.access
/etc/login.defs
/usr/bin/chage
/usr/bin/chfn
/usr/bin/chsh
/usr/bin/expiry
/usr/bin/faillog
/usr/bin/gpasswd
/usr/bin/lastlog
/usr/bin/login
/usr/bin/newgidmap
/usr/bin/newgrp
/usr/bin/newuidmap
/usr/bin/passwd
/usr/bin/sg
/usr/bin/su
/usr/sbin/chgpasswd
/usr/sbin/chpasswd
/usr/sbin/groupadd
/usr/sbin/groupdel
/usr/sbin/groupmems
/usr/sbin/groupmod
/usr/sbin/grpck
/usr/sbin/grpconv
/usr/sbin/grpunconv
/usr/sbin/logoutd
/usr/sbin/newusers
/usr/sbin/nologin
/usr/sbin/pwck
/usr/sbin/pwconv
/usr/sbin/pwunconv
/usr/sbin/useradd
/usr/sbin/userdel
/usr/sbin/usermod
/usr/sbin/vigr
/usr/sbin/vipw
/usr/share/locale/bs/LC_MESSAGES/shadow.mo
/usr/share/locale/ca/LC_MESSAGES/shadow.mo
/usr/share/locale/cs/LC_MESSAGES/shadow.mo
/usr/share/locale/da/LC_MESSAGES/shadow.mo
/usr/share/locale/de/LC_MESSAGES/shadow.mo
/usr/share/locale/dz/LC_MESSAGES/shadow.mo
/usr/share/locale/el/LC_MESSAGES/shadow.mo
/usr/share/locale/es/LC_MESSAGES/shadow.mo
/usr/share/locale/eu/LC_MESSAGES/shadow.mo
/usr/share/locale/fi/LC_MESSAGES/shadow.mo
/usr/share/locale/fr/LC_MESSAGES/shadow.mo
/usr/share/locale/gl/LC_MESSAGES/shadow.mo
/usr/share/locale/he/LC_MESSAGES/shadow.mo
/usr/share/locale/hu/LC_MESSAGES/shadow.mo
/usr/share/locale/id/LC_MESSAGES/shadow.mo
/usr/share/locale/it/LC_MESSAGES/shadow.mo
/usr/share/locale/ja/LC_MESSAGES/shadow.mo
/usr/share/locale/kk/LC_MESSAGES/shadow.mo
/usr/share/locale/km/LC_MESSAGES/shadow.mo
/usr/share/locale/ko/LC_MESSAGES/shadow.mo
/usr/share/locale/nb/LC_MESSAGES/shadow.mo
/usr/share/locale/ne/LC_MESSAGES/shadow.mo
/usr/share/locale/nl/LC_MESSAGES/shadow.mo
/usr/share/locale/nn/LC_MESSAGES/shadow.mo
/usr/share/locale/pl/LC_MESSAGES/shadow.mo
/usr/share/locale/pt/LC_MESSAGES/shadow.mo
/usr/share/locale/pt_BR/LC_MESSAGES/shadow.mo
/usr/share/locale/ro/LC_MESSAGES/shadow.mo
/usr/share/locale/ru/LC_MESSAGES/shadow.mo
/usr/share/locale/sk/LC_MESSAGES/shadow.mo
/usr/share/locale/sq/LC_MESSAGES/shadow.mo
/usr/share/locale/sv/LC_MESSAGES/shadow.mo
/usr/share/locale/tl/LC_MESSAGES/shadow.mo
/usr/share/locale/tr/LC_MESSAGES/shadow.mo
/usr/share/locale/uk/LC_MESSAGES/shadow.mo
/usr/share/locale/vi/LC_MESSAGES/shadow.mo
/usr/share/locale/zh_CN/LC_MESSAGES/shadow.mo
/usr/share/locale/zh_TW/LC_MESSAGES/shadow.mo
/usr/share/man/cs/man1/expiry.1.gz
/usr/share/man/cs/man1/gpasswd.1.gz
/usr/share/man/cs/man1/su.1.gz
/usr/share/man/cs/man5/faillog.5.gz
/usr/share/man/cs/man5/gshadow.5.gz
/usr/share/man/cs/man5/shadow.5.gz
/usr/share/man/cs/man8/faillog.8.gz
/usr/share/man/cs/man8/groupadd.8.gz
/usr/share/man/cs/man8/groupdel.8.gz
/usr/share/man/cs/man8/groupmod.8.gz
/usr/share/man/cs/man8/grpck.8.gz
/usr/share/man/cs/man8/lastlog.8.gz
/usr/share/man/cs/man8/nologin.8.gz
/usr/share/man/cs/man8/vipw.8.gz
/usr/share/man/da/man1/chfn.1.gz
/usr/share/man/da/man1/newgrp.1.gz
/usr/share/man/da/man1/sg.1.gz
/usr/share/man/da/man5/gshadow.5.gz
/usr/share/man/da/man8/groupdel.8.gz
/usr/share/man/da/man8/logoutd.8.gz
/usr/share/man/da/man8/nologin.8.gz
/usr/share/man/da/man8/vigr.8.gz
/usr/share/man/da/man8/vipw.8.gz
/usr/share/man/de/man1/chage.1.gz
/usr/share/man/de/man1/chfn.1.gz
/usr/share/man/de/man1/chsh.1.gz
/usr/share/man/de/man1/expiry.1.gz
/usr/share/man/de/man1/gpasswd.1.gz
/usr/share/man/de/man1/login.1.gz
/usr/share/man/de/man1/newgrp.1.gz
/usr/share/man/de/man1/passwd.1.gz
/usr/share/man/de/man1/sg.1.gz
/usr/share/man/de/man1/su.1.gz
/usr/share/man/de/man3/shadow.3.gz
/usr/share/man/de/man5/faillog.5.gz
/usr/share/man/de/man5/gshadow.5.gz
/usr/share/man/de/man5/limits.5.gz
/usr/share/man/de/man5/login.access.5.gz
/usr/share/man/de/man5/login.defs.5.gz
/usr/share/man/de/man5/porttime.5.gz
/usr/share/man/de/man5/shadow.5.gz
/usr/share/man/de/man5/suauth.5.gz
/usr/share/man/de/man8/chgpasswd.8.gz
/usr/share/man/de/man8/chpasswd.8.gz
/usr/share/man/de/man8/faillog.8.gz
/usr/share/man/de/man8/groupadd.8.gz
/usr/share/man/de/man8/groupdel.8.gz
/usr/share/man/de/man8/groupmems.8.gz
/usr/share/man/de/man8/groupmod.8.gz
/usr/share/man/de/man8/grpck.8.gz
/usr/share/man/de/man8/grpconv.8.gz
/usr/share/man/de/man8/grpunconv.8.gz
/usr/share/man/de/man8/lastlog.8.gz
/usr/share/man/de/man8/logoutd.8.gz
/usr/share/man/de/man8/newusers.8.gz
/usr/share/man/de/man8/nologin.8.gz
/usr/share/man/de/man8/pwck.8.gz
/usr/share/man/de/man8/pwconv.8.gz
/usr/share/man/de/man8/pwunconv.8.gz
/usr/share/man/de/man8/useradd.8.gz
/usr/share/man/de/man8/userdel.8.gz
/usr/share/man/de/man8/usermod.8.gz
/usr/share/man/de/man8/vigr.8.gz
/usr/share/man/de/man8/vipw.8.gz
/usr/share/man/fi/man1/chfn.1.gz
/usr/share/man/fi/man1/chsh.1.gz
/usr/share/man/fi/man1/su.1.gz
/usr/share/man/fr/man1/chage.1.gz
/usr/share/man/fr/man1/chfn.1.gz
/usr/share/man/fr/man1/chsh.1.gz
/usr/share/man/fr/man1/expiry.1.gz
/usr/share/man/fr/man1/gpasswd.1.gz
/usr/share/man/fr/man1/login.1.gz
/usr/share/man/fr/man1/newgidmap.1.gz
/usr/share/man/fr/man1/newgrp.1.gz
/usr/share/man/fr/man1/newuidmap.1.gz
/usr/share/man/fr/man1/passwd.1.gz
/usr/share/man/fr/man1/sg.1.gz
/usr/share/man/fr/man1/su.1.gz
/usr/share/man/fr/man3/shadow.3.gz
/usr/share/man/fr/man5/faillog.5.gz
/usr/share/man/fr/man5/gshadow.5.gz
/usr/share/man/fr/man5/limits.5.gz
/usr/share/man/fr/man5/login.access.5.gz
/usr/share/man/fr/man5/login.defs.5.gz
/usr/share/man/fr/man5/porttime.5.gz
/usr/share/man/fr/man5/shadow.5.gz
/usr/share/man/fr/man5/suauth.5.gz
/usr/share/man/fr/man5/subgid.5.gz
/usr/share/man/fr/man5/subuid.5.gz
/usr/share/man/fr/man8/chgpasswd.8.gz
/usr/share/man/fr/man8/chpasswd.8.gz
/usr/share/man/fr/man8/faillog.8.gz
/usr/share/man/fr/man8/groupadd.8.gz
/usr/share/man/fr/man8/groupdel.8.gz
/usr/share/man/fr/man8/groupmems.8.gz
/usr/share/man/fr/man8/groupmod.8.gz
/usr/share/man/fr/man8/grpck.8.gz
/usr/share/man/fr/man8/grpconv.8.gz
/usr/share/man/fr/man8/grpunconv.8.gz
/usr/share/man/fr/man8/lastlog.8.gz
/usr/share/man/fr/man8/logoutd.8.gz
/usr/share/man/fr/man8/newusers.8.gz
/usr/share/man/fr/man8/nologin.8.gz
/usr/share/man/fr/man8/pwck.8.gz
/usr/share/man/fr/man8/pwconv.8.gz
/usr/share/man/fr/man8/pwunconv.8.gz
/usr/share/man/fr/man8/useradd.8.gz
/usr/share/man/fr/man8/userdel.8.gz
/usr/share/man/fr/man8/usermod.8.gz
/usr/share/man/fr/man8/vigr.8.gz
/usr/share/man/fr/man8/vipw.8.gz
/usr/share/man/hu/man1/chsh.1.gz
/usr/share/man/hu/man1/gpasswd.1.gz
/usr/share/man/hu/man1/login.1.gz
/usr/share/man/hu/man1/newgrp.1.gz
/usr/share/man/hu/man1/passwd.1.gz
/usr/share/man/hu/man1/sg.1.gz
/usr/share/man/hu/man1/su.1.gz
/usr/share/man/hu/man8/lastlog.8.gz
/usr/share/man/id/man1/chsh.1.gz
/usr/share/man/id/man1/login.1.gz
/usr/share/man/id/man8/useradd.8.gz
/usr/share/man/it/man1/chage.1.gz
/usr/share/man/it/man1/chfn.1.gz
/usr/share/man/it/man1/chsh.1.gz
/usr/share/man/it/man1/expiry.1.gz
/usr/share/man/it/man1/gpasswd.1.gz
/usr/share/man/it/man1/login.1.gz
/usr/share/man/it/man1/newgrp.1.gz
/usr/share/man/it/man1/passwd.1.gz
/usr/share/man/it/man1/sg.1.gz
/usr/share/man/it/man1/su.1.gz
/usr/share/man/it/man3/shadow.3.gz
/usr/share/man/it/man5/faillog.5.gz
/usr/share/man/it/man5/gshadow.5.gz
/usr/share/man/it/man5/limits.5.gz
/usr/share/man/it/man5/login.access.5.gz
/usr/share/man/it/man5/login.defs.5.gz
/usr/share/man/it/man5/porttime.5.gz
/usr/share/man/it/man5/shadow.5.gz
/usr/share/man/it/man5/suauth.5.gz
/usr/share/man/it/man8/chgpasswd.8.gz
/usr/share/man/it/man8/chpasswd.8.gz
/usr/share/man/it/man8/faillog.8.gz
/usr/share/man/it/man8/groupadd.8.gz
/usr/share/man/it/man8/groupdel.8.gz
/usr/share/man/it/man8/groupmems.8.gz
/usr/share/man/it/man8/groupmod.8.gz
/usr/share/man/it/man8/grpck.8.gz
/usr/share/man/it/man8/grpconv.8.gz
/usr/share/man/it/man8/grpunconv.8.gz
/usr/share/man/it/man8/lastlog.8.gz
/usr/share/man/it/man8/logoutd.8.gz
/usr/share/man/it/man8/newusers.8.gz
/usr/share/man/it/man8/nologin.8.gz
/usr/share/man/it/man8/pwck.8.gz
/usr/share/man/it/man8/pwconv.8.gz
/usr/share/man/it/man8/pwunconv.8.gz
/usr/share/man/it/man8/useradd.8.gz
/usr/share/man/it/man8/userdel.8.gz
/usr/share/man/it/man8/usermod.8.gz
/usr/share/man/it/man8/vigr.8.gz
/usr/share/man/it/man8/vipw.8.gz
/usr/share/man/ja/man1/chage.1.gz
/usr/share/man/ja/man1/chfn.1.gz
/usr/share/man/ja/man1/chsh.1.gz
/usr/share/man/ja/man1/expiry.1.gz
/usr/share/man/ja/man1/gpasswd.1.gz
/usr/share/man/ja/man1/login.1.gz
/usr/share/man/ja/man1/newgrp.1.gz
/usr/share/man/ja/man1/passwd.1.gz
/usr/share/man/ja/man1/sg.1.gz
/usr/share/man/ja/man1/su.1.gz
/usr/share/man/ja/man5/faillog.5.gz
/usr/share/man/ja/man5/limits.5.gz
/usr/share/man/ja/man5/login.access.5.gz
/usr/share/man/ja/man5/login.defs.5.gz
/usr/share/man/ja/man5/porttime.5.gz
/usr/share/man/ja/man5/shadow.5.gz
/usr/share/man/ja/man5/suauth.5.gz
/usr/share/man/ja/man8/chpasswd.8.gz
/usr/share/man/ja/man8/faillog.8.gz
/usr/share/man/ja/man8/groupadd.8.gz
/usr/share/man/ja/man8/groupdel.8.gz
/usr/share/man/ja/man8/groupmod.8.gz
/usr/share/man/ja/man8/grpck.8.gz
/usr/share/man/ja/man8/grpconv.8.gz
/usr/share/man/ja/man8/grpunconv.8.gz
/usr/share/man/ja/man8/lastlog.8.gz
/usr/share/man/ja/man8/logoutd.8.gz
/usr/share/man/ja/man8/newusers.8.gz
/usr/share/man/ja/man8/pwck.8.gz
/usr/share/man/ja/man8/pwconv.8.gz
/usr/share/man/ja/man8/pwunconv.8.gz
/usr/share/man/ja/man8/useradd.8.gz
/usr/share/man/ja/man8/userdel.8.gz
/usr/share/man/ja/man8/usermod.8.gz
/usr/share/man/ja/man8/vigr.8.gz
/usr/share/man/ja/man8/vipw.8.gz
/usr/share/man/ko/man1/chfn.1.gz
/usr/share/man/ko/man1/chsh.1.gz
/usr/share/man/ko/man1/login.1.gz
/usr/share/man/ko/man1/su.1.gz
/usr/share/man/ko/man8/vigr.8.gz
/usr/share/man/ko/man8/vipw.8.gz
/usr/share/man/man1/chage.1.gz
/usr/share/man/man1/chfn.1.gz
/usr/share/man/man1/chsh.1.gz
/usr/share/man/man1/expiry.1.gz
/usr/share/man/man1/gpasswd.1.gz
/usr/share/man/man1/login.1.gz
/usr/share/man/man1/newgidmap.1.gz
/usr/share/man/man1/newgrp.1.gz
/usr/share/man/man1/newuidmap.1.gz
/usr/share/man/man1/passwd.1.gz
/usr/share/man/man1/sg.1.gz
/usr/share/man/man1/su.1.gz
/usr/share/man/man3/shadow.3.gz
/usr/share/man/man5/faillog.5.gz
/usr/share/man/man5/gshadow.5.gz
/usr/share/man/man5/limits.5.gz
/usr/share/man/man5/login.access.5.gz
/usr/share/man/man5/login.defs.5.gz
/usr/share/man/man5/porttime.5.gz
/usr/share/man/man5/shadow.5.gz
/usr/share/man/man5/suauth.5.gz
/usr/share/man/man5/subgid.5.gz
/usr/share/man/man5/subuid.5.gz
/usr/share/man/man8/chgpasswd.8.gz
/usr/share/man/man8/chpasswd.8.gz
/usr/share/man/man8/faillog.8.gz
/usr/share/man/man8/groupadd.8.gz
/usr/share/man/man8/groupdel.8.gz
/usr/share/man/man8/groupmems.8.gz
/usr/share/man/man8/groupmod.8.gz
/usr/share/man/man8/grpck.8.gz
/usr/share/man/man8/grpconv.8.gz
/usr/share/man/man8/grpunconv.8.gz
/usr/share/man/man8/lastlog.8.gz
/usr/share/man/man8/logoutd.8.gz
/usr/share/man/man8/newusers.8.gz
/usr/share/man/man8/nologin.8.gz
/usr/share/man/man8/pwck.8.gz
/usr/share/man/man8/pwconv.8.gz
/usr/share/man/man8/pwunconv.8.gz
/usr/share/man/man8/useradd.8.gz
/usr/share/man/man8/userdel.8.gz
/usr/share/man/man8/usermod.8.gz
/usr/share/man/man8/vigr.8.gz
/usr/share/man/man8/vipw.8.gz
/usr/share/man/pl/man1/chage.1.gz
/usr/share/man/pl/man1/chsh.1.gz
/usr/share/man/pl/man1/expiry.1.gz
/usr/share/man/pl/man1/newgrp.1.gz
/usr/share/man/pl/man1/sg.1.gz
/usr/share/man/pl/man3/shadow.3.gz
/usr/share/man/pl/man5/faillog.5.gz
/usr/share/man/pl/man5/porttime.5.gz
/usr/share/man/pl/man8/faillog.8.gz
/usr/share/man/pl/man8/groupadd.8.gz
/usr/share/man/pl/man8/groupdel.8.gz
/usr/share/man/pl/man8/groupmems.8.gz
/usr/share/man/pl/man8/groupmod.8.gz
/usr/share/man/pl/man8/grpck.8.gz
/usr/share/man/pl/man8/lastlog.8.gz
/usr/share/man/pl/man8/logoutd.8.gz
/usr/share/man/pl/man8/userdel.8.gz
/usr/share/man/pl/man8/usermod.8.gz
/usr/share/man/pl/man8/vigr.8.gz
/usr/share/man/pl/man8/vipw.8.gz
/usr/share/man/pt_BR/man1/gpasswd.1.gz
/usr/share/man/pt_BR/man5/shadow.5.gz
/usr/share/man/pt_BR/man8/groupadd.8.gz
/usr/share/man/pt_BR/man8/groupdel.8.gz
/usr/share/man/pt_BR/man8/groupmod.8.gz
/usr/share/man/ru/man1/chage.1.gz
/usr/share/man/ru/man1/chfn.1.gz
/usr/share/man/ru/man1/chsh.1.gz
/usr/share/man/ru/man1/expiry.1.gz
/usr/share/man/ru/man1/gpasswd.1.gz
/usr/share/man/ru/man1/login.1.gz
/usr/share/man/ru/man1/newgrp.1.gz
/usr/share/man/ru/man1/passwd.1.gz
/usr/share/man/ru/man1/sg.1.gz
/usr/share/man/ru/man1/su.1.gz
/usr/share/man/ru/man3/shadow.3.gz
/usr/share/man/ru/man5/faillog.5.gz
/usr/share/man/ru/man5/gshadow.5.gz
/usr/share/man/ru/man5/limits.5.gz
/usr/share/man/ru/man5/login.access.5.gz
/usr/share/man/ru/man5/login.defs.5.gz
/usr/share/man/ru/man5/porttime.5.gz
/usr/share/man/ru/man5/shadow.5.gz
/usr/share/man/ru/man5/suauth.5.gz
/usr/share/man/ru/man8/chgpasswd.8.gz
/usr/share/man/ru/man8/chpasswd.8.gz
/usr/share/man/ru/man8/faillog.8.gz
/usr/share/man/ru/man8/groupadd.8.gz
/usr/share/man/ru/man8/groupdel.8.gz
/usr/share/man/ru/man8/groupmems.8.gz
/usr/share/man/ru/man8/groupmod.8.gz
/usr/share/man/ru/man8/grpck.8.gz
/usr/share/man/ru/man8/grpconv.8.gz
/usr/share/man/ru/man8/grpunconv.8.gz
/usr/share/man/ru/man8/lastlog.8.gz
/usr/share/man/ru/man8/logoutd.8.gz
/usr/share/man/ru/man8/newusers.8.gz
/usr/share/man/ru/man8/nologin.8.gz
/usr/share/man/ru/man8/pwck.8.gz
/usr/share/man/ru/man8/pwconv.8.gz
/usr/share/man/ru/man8/pwunconv.8.gz
/usr/share/man/ru/man8/useradd.8.gz
/usr/share/man/ru/man8/userdel.8.gz
/usr/share/man/ru/man8/usermod.8.gz
/usr/share/man/ru/man8/vigr.8.gz
/usr/share/man/ru/man8/vipw.8.gz
/usr/share/man/sv/man1/chage.1.gz
/usr/share/man/sv/man1/chsh.1.gz
/usr/share/man/sv/man1/expiry.1.gz
/usr/share/man/sv/man1/newgrp.1.gz
/usr/share/man/sv/man1/passwd.1.gz
/usr/share/man/sv/man1/sg.1.gz
/usr/share/man/sv/man3/shadow.3.gz
/usr/share/man/sv/man5/faillog.5.gz
/usr/share/man/sv/man5/gshadow.5.gz
/usr/share/man/sv/man5/limits.5.gz
/usr/share/man/sv/man5/porttime.5.gz
/usr/share/man/sv/man5/suauth.5.gz
/usr/share/man/sv/man8/faillog.8.gz
/usr/share/man/sv/man8/groupadd.8.gz
/usr/share/man/sv/man8/groupdel.8.gz
/usr/share/man/sv/man8/groupmems.8.gz
/usr/share/man/sv/man8/groupmod.8.gz
/usr/share/man/sv/man8/grpck.8.gz
/usr/share/man/sv/man8/lastlog.8.gz
/usr/share/man/sv/man8/logoutd.8.gz
/usr/share/man/sv/man8/nologin.8.gz
/usr/share/man/sv/man8/pwck.8.gz
/usr/share/man/sv/man8/userdel.8.gz
/usr/share/man/sv/man8/vigr.8.gz
/usr/share/man/sv/man8/vipw.8.gz
/usr/share/man/tr/man1/chage.1.gz
/usr/share/man/tr/man1/chfn.1.gz
/usr/share/man/tr/man1/login.1.gz
/usr/share/man/tr/man1/passwd.1.gz
/usr/share/man/tr/man1/su.1.gz
/usr/share/man/tr/man5/shadow.5.gz
/usr/share/man/tr/man8/groupadd.8.gz
/usr/share/man/tr/man8/groupdel.8.gz
/usr/share/man/tr/man8/groupmod.8.gz
/usr/share/man/tr/man8/useradd.8.gz
/usr/share/man/tr/man8/userdel.8.gz
/usr/share/man/tr/man8/usermod.8.gz
/usr/share/man/zh_CN/man1/chage.1.gz
/usr/share/man/zh_CN/man1/chfn.1.gz
/usr/share/man/zh_CN/man1/chsh.1.gz
/usr/share/man/zh_CN/man1/expiry.1.gz
/usr/share/man/zh_CN/man1/gpasswd.1.gz
/usr/share/man/zh_CN/man1/login.1.gz
/usr/share/man/zh_CN/man1/newgrp.1.gz
/usr/share/man/zh_CN/man1/passwd.1.gz
/usr/share/man/zh_CN/man1/sg.1.gz
/usr/share/man/zh_CN/man1/su.1.gz
/usr/share/man/zh_CN/man3/shadow.3.gz
/usr/share/man/zh_CN/man5/faillog.5.gz
/usr/share/man/zh_CN/man5/gshadow.5.gz
/usr/share/man/zh_CN/man5/limits.5.gz
/usr/share/man/zh_CN/man5/login.access.5.gz
/usr/share/man/zh_CN/man5/login.defs.5.gz
/usr/share/man/zh_CN/man5/porttime.5.gz
/usr/share/man/zh_CN/man5/shadow.5.gz
/usr/share/man/zh_CN/man5/suauth.5.gz
/usr/share/man/zh_CN/man8/chgpasswd.8.gz
/usr/share/man/zh_CN/man8/chpasswd.8.gz
/usr/share/man/zh_CN/man8/faillog.8.gz
/usr/share/man/zh_CN/man8/groupadd.8.gz
/usr/share/man/zh_CN/man8/groupdel.8.gz
/usr/share/man/zh_CN/man8/groupmems.8.gz
/usr/share/man/zh_CN/man8/groupmod.8.gz
/usr/share/man/zh_CN/man8/grpck.8.gz
/usr/share/man/zh_CN/man8/grpconv.8.gz
/usr/share/man/zh_CN/man8/grpunconv.8.gz
/usr/share/man/zh_CN/man8/lastlog.8.gz
/usr/share/man/zh_CN/man8/logoutd.8.gz
/usr/share/man/zh_CN/man8/newusers.8.gz
/usr/share/man/zh_CN/man8/nologin.8.gz
/usr/share/man/zh_CN/man8/pwck.8.gz
/usr/share/man/zh_CN/man8/pwconv.8.gz
/usr/share/man/zh_CN/man8/pwunconv.8.gz
/usr/share/man/zh_CN/man8/useradd.8.gz
/usr/share/man/zh_CN/man8/userdel.8.gz
/usr/share/man/zh_CN/man8/usermod.8.gz
/usr/share/man/zh_CN/man8/vigr.8.gz
/usr/share/man/zh_CN/man8/vipw.8.gz
/usr/share/man/zh_TW/man1/chfn.1.gz
/usr/share/man/zh_TW/man1/chsh.1.gz
/usr/share/man/zh_TW/man1/newgrp.1.gz
/usr/share/man/zh_TW/man1/su.1.gz
/usr/share/man/zh_TW/man8/chpasswd.8.gz
/usr/share/man/zh_TW/man8/groupadd.8.gz
/usr/share/man/zh_TW/man8/groupdel.8.gz
/usr/share/man/zh_TW/man8/groupmod.8.gz
/usr/share/man/zh_TW/man8/useradd.8.gz
/usr/share/man/zh_TW/man8/userdel.8.gz
/usr/share/man/zh_TW/man8/usermod.8.gz


%changelog
# let's skip this for now
