Name:       ImageMagick
Version:    7.0.8
Release:    1
Summary:    TODO
License:    GPL3
Prefix:     /usr
Source0:    %{name}-7.0.8-27.tar.xz

%description
TODO

%prep
%setup -a 0 -n ImageMagick-7.0.8-27

%build
%configure  --sysconfdir=/etc \
            --enable-hdri     \
            --with-modules    \
            --with-perl       \
            --disable-static
%make_build


%install    
rm -rf %{buildroot}
%make_install
rm -vf %{buildroot}%{_infodir}/dir*

%files
/etc/ImageMagick-7/colors.xml
/etc/ImageMagick-7/delegates.xml
/etc/ImageMagick-7/log.xml
/etc/ImageMagick-7/mime.xml
/etc/ImageMagick-7/policy.xml
/etc/ImageMagick-7/quantization-table.xml
/etc/ImageMagick-7/thresholds.xml
/etc/ImageMagick-7/type-apple.xml
/etc/ImageMagick-7/type-dejavu.xml
/etc/ImageMagick-7/type-ghostscript.xml
/etc/ImageMagick-7/type-urw-base35.xml
/etc/ImageMagick-7/type-windows.xml
/etc/ImageMagick-7/type.xml
/usr/bin/Magick++-config
/usr/bin/MagickCore-config
/usr/bin/MagickWand-config
/usr/bin/animate
/usr/bin/compare
/usr/bin/composite
/usr/bin/conjure
/usr/bin/convert
/usr/bin/display
/usr/bin/identify
/usr/bin/import
/usr/bin/magick
/usr/bin/magick-script
/usr/bin/mogrify
/usr/bin/montage
/usr/bin/stream
/usr/include/ImageMagick-7/Magick++.h
/usr/include/ImageMagick-7/Magick++/Blob.h
/usr/include/ImageMagick-7/Magick++/CoderInfo.h
/usr/include/ImageMagick-7/Magick++/Color.h
/usr/include/ImageMagick-7/Magick++/Drawable.h
/usr/include/ImageMagick-7/Magick++/Exception.h
/usr/include/ImageMagick-7/Magick++/Functions.h
/usr/include/ImageMagick-7/Magick++/Geometry.h
/usr/include/ImageMagick-7/Magick++/Image.h
/usr/include/ImageMagick-7/Magick++/Include.h
/usr/include/ImageMagick-7/Magick++/Montage.h
/usr/include/ImageMagick-7/Magick++/Pixels.h
/usr/include/ImageMagick-7/Magick++/ResourceLimits.h
/usr/include/ImageMagick-7/Magick++/STL.h
/usr/include/ImageMagick-7/Magick++/SecurityPolicy.h
/usr/include/ImageMagick-7/Magick++/Statistic.h
/usr/include/ImageMagick-7/Magick++/TypeMetric.h
/usr/include/ImageMagick-7/MagickCore/MagickCore.h
/usr/include/ImageMagick-7/MagickCore/animate.h
/usr/include/ImageMagick-7/MagickCore/annotate.h
/usr/include/ImageMagick-7/MagickCore/artifact.h
/usr/include/ImageMagick-7/MagickCore/attribute.h
/usr/include/ImageMagick-7/MagickCore/blob.h
/usr/include/ImageMagick-7/MagickCore/cache-view.h
/usr/include/ImageMagick-7/MagickCore/cache.h
/usr/include/ImageMagick-7/MagickCore/channel.h
/usr/include/ImageMagick-7/MagickCore/cipher.h
/usr/include/ImageMagick-7/MagickCore/client.h
/usr/include/ImageMagick-7/MagickCore/coder.h
/usr/include/ImageMagick-7/MagickCore/color.h
/usr/include/ImageMagick-7/MagickCore/colormap.h
/usr/include/ImageMagick-7/MagickCore/colorspace.h
/usr/include/ImageMagick-7/MagickCore/compare.h
/usr/include/ImageMagick-7/MagickCore/composite.h
/usr/include/ImageMagick-7/MagickCore/compress.h
/usr/include/ImageMagick-7/MagickCore/configure.h
/usr/include/ImageMagick-7/MagickCore/constitute.h
/usr/include/ImageMagick-7/MagickCore/decorate.h
/usr/include/ImageMagick-7/MagickCore/delegate.h
/usr/include/ImageMagick-7/MagickCore/deprecate.h
/usr/include/ImageMagick-7/MagickCore/display.h
/usr/include/ImageMagick-7/MagickCore/distort.h
/usr/include/ImageMagick-7/MagickCore/distribute-cache.h
/usr/include/ImageMagick-7/MagickCore/draw.h
/usr/include/ImageMagick-7/MagickCore/effect.h
/usr/include/ImageMagick-7/MagickCore/enhance.h
/usr/include/ImageMagick-7/MagickCore/exception.h
/usr/include/ImageMagick-7/MagickCore/feature.h
/usr/include/ImageMagick-7/MagickCore/fourier.h
/usr/include/ImageMagick-7/MagickCore/fx.h
/usr/include/ImageMagick-7/MagickCore/gem.h
/usr/include/ImageMagick-7/MagickCore/geometry.h
/usr/include/ImageMagick-7/MagickCore/histogram.h
/usr/include/ImageMagick-7/MagickCore/identify.h
/usr/include/ImageMagick-7/MagickCore/image-view.h
/usr/include/ImageMagick-7/MagickCore/image.h
/usr/include/ImageMagick-7/MagickCore/layer.h
/usr/include/ImageMagick-7/MagickCore/linked-list.h
/usr/include/ImageMagick-7/MagickCore/list.h
/usr/include/ImageMagick-7/MagickCore/locale_.h
/usr/include/ImageMagick-7/MagickCore/log.h
/usr/include/ImageMagick-7/MagickCore/magic.h
/usr/include/ImageMagick-7/MagickCore/magick-baseconfig.h
/usr/include/ImageMagick-7/MagickCore/magick-config.h
/usr/include/ImageMagick-7/MagickCore/magick-type.h
/usr/include/ImageMagick-7/MagickCore/magick.h
/usr/include/ImageMagick-7/MagickCore/matrix.h
/usr/include/ImageMagick-7/MagickCore/memory_.h
/usr/include/ImageMagick-7/MagickCore/method-attribute.h
/usr/include/ImageMagick-7/MagickCore/methods.h
/usr/include/ImageMagick-7/MagickCore/mime.h
/usr/include/ImageMagick-7/MagickCore/module.h
/usr/include/ImageMagick-7/MagickCore/monitor.h
/usr/include/ImageMagick-7/MagickCore/montage.h
/usr/include/ImageMagick-7/MagickCore/morphology.h
/usr/include/ImageMagick-7/MagickCore/nt-base.h
/usr/include/ImageMagick-7/MagickCore/opencl.h
/usr/include/ImageMagick-7/MagickCore/option.h
/usr/include/ImageMagick-7/MagickCore/paint.h
/usr/include/ImageMagick-7/MagickCore/pixel-accessor.h
/usr/include/ImageMagick-7/MagickCore/pixel.h
/usr/include/ImageMagick-7/MagickCore/policy.h
/usr/include/ImageMagick-7/MagickCore/prepress.h
/usr/include/ImageMagick-7/MagickCore/profile.h
/usr/include/ImageMagick-7/MagickCore/property.h
/usr/include/ImageMagick-7/MagickCore/quantize.h
/usr/include/ImageMagick-7/MagickCore/quantum.h
/usr/include/ImageMagick-7/MagickCore/random_.h
/usr/include/ImageMagick-7/MagickCore/registry.h
/usr/include/ImageMagick-7/MagickCore/resample.h
/usr/include/ImageMagick-7/MagickCore/resize.h
/usr/include/ImageMagick-7/MagickCore/resource_.h
/usr/include/ImageMagick-7/MagickCore/segment.h
/usr/include/ImageMagick-7/MagickCore/semaphore.h
/usr/include/ImageMagick-7/MagickCore/shear.h
/usr/include/ImageMagick-7/MagickCore/signature.h
/usr/include/ImageMagick-7/MagickCore/splay-tree.h
/usr/include/ImageMagick-7/MagickCore/static.h
/usr/include/ImageMagick-7/MagickCore/statistic.h
/usr/include/ImageMagick-7/MagickCore/stream.h
/usr/include/ImageMagick-7/MagickCore/string_.h
/usr/include/ImageMagick-7/MagickCore/studio.h
/usr/include/ImageMagick-7/MagickCore/threshold.h
/usr/include/ImageMagick-7/MagickCore/timer.h
/usr/include/ImageMagick-7/MagickCore/token.h
/usr/include/ImageMagick-7/MagickCore/transform.h
/usr/include/ImageMagick-7/MagickCore/type.h
/usr/include/ImageMagick-7/MagickCore/utility.h
/usr/include/ImageMagick-7/MagickCore/version.h
/usr/include/ImageMagick-7/MagickCore/vision.h
/usr/include/ImageMagick-7/MagickCore/widget.h
/usr/include/ImageMagick-7/MagickCore/xml-tree.h
/usr/include/ImageMagick-7/MagickCore/xwindow.h
/usr/include/ImageMagick-7/MagickWand/MagickWand.h
/usr/include/ImageMagick-7/MagickWand/animate.h
/usr/include/ImageMagick-7/MagickWand/compare.h
/usr/include/ImageMagick-7/MagickWand/composite.h
/usr/include/ImageMagick-7/MagickWand/conjure.h
/usr/include/ImageMagick-7/MagickWand/convert.h
/usr/include/ImageMagick-7/MagickWand/deprecate.h
/usr/include/ImageMagick-7/MagickWand/display.h
/usr/include/ImageMagick-7/MagickWand/drawing-wand.h
/usr/include/ImageMagick-7/MagickWand/identify.h
/usr/include/ImageMagick-7/MagickWand/import.h
/usr/include/ImageMagick-7/MagickWand/magick-cli.h
/usr/include/ImageMagick-7/MagickWand/magick-image.h
/usr/include/ImageMagick-7/MagickWand/magick-property.h
/usr/include/ImageMagick-7/MagickWand/method-attribute.h
/usr/include/ImageMagick-7/MagickWand/mogrify.h
/usr/include/ImageMagick-7/MagickWand/montage.h
/usr/include/ImageMagick-7/MagickWand/operation.h
/usr/include/ImageMagick-7/MagickWand/pixel-iterator.h
/usr/include/ImageMagick-7/MagickWand/pixel-wand.h
/usr/include/ImageMagick-7/MagickWand/stream.h
/usr/include/ImageMagick-7/MagickWand/wand-view.h
/usr/include/ImageMagick-7/MagickWand/wandcli.h
/usr/lib/perl5/5.28.1/x86_64-linux-thread-multi/perllocal.pod
/usr/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/Image/Magick.pm
/usr/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/Image/Magick/Q16HDRI.pm
/usr/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/auto/Image/Magick/.packlist
/usr/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/auto/Image/Magick/Q16HDRI/Q16HDRI.so
/usr/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/auto/Image/Magick/Q16HDRI/autosplit.ix
/usr/lib64/ImageMagick-7.0.8/config-Q16HDRI/configure.xml
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/aai.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/aai.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/art.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/art.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/avs.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/avs.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/bgr.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/bgr.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/bmp.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/bmp.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/braille.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/braille.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cals.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cals.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/caption.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/caption.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cin.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cin.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cip.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cip.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/clip.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/clip.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cmyk.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cmyk.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cube.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cube.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cut.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/cut.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dcm.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dcm.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dds.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dds.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/debug.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/debug.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dib.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dib.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dng.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dng.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dot.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dot.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dpx.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/dpx.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/fax.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/fax.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/fits.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/fits.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/gif.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/gif.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/gradient.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/gradient.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/gray.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/gray.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/hald.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/hald.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/hdr.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/hdr.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/histogram.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/histogram.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/hrz.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/hrz.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/html.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/html.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/icon.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/icon.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/info.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/info.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/inline.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/inline.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ipl.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ipl.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/jnx.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/jnx.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/jpeg.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/jpeg.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/json.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/json.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/label.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/label.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mac.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mac.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/magick.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/magick.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/map.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/map.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mask.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mask.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mat.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mat.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/matte.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/matte.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/meta.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/meta.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/miff.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/miff.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mono.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mono.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mpc.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mpc.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mpeg.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mpeg.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mpr.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mpr.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/msl.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/msl.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mtv.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mtv.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mvg.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/mvg.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/null.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/null.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/otb.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/otb.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/palm.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/palm.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pango.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pango.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pattern.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pattern.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pcd.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pcd.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pcl.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pcl.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pcx.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pcx.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pdb.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pdb.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pdf.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pdf.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pes.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pes.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pgx.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pgx.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pict.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pict.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pix.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pix.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/plasma.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/plasma.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/png.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/png.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pnm.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pnm.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ps.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ps.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ps2.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ps2.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ps3.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ps3.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/psd.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/psd.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pwp.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/pwp.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/raw.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/raw.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rgb.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rgb.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rgf.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rgf.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rla.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rla.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rle.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/rle.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/scr.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/scr.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sct.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sct.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sfw.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sfw.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sgi.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sgi.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sixel.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sixel.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/stegano.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/stegano.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sun.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/sun.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/svg.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/svg.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/tga.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/tga.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/thumbnail.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/thumbnail.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/tile.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/tile.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/tim.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/tim.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ttf.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ttf.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/txt.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/txt.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/uil.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/uil.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/url.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/url.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/uyvy.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/uyvy.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/vicar.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/vicar.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/vid.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/vid.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/viff.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/viff.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/vips.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/vips.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/wbmp.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/wbmp.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/wpg.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/wpg.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/x.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/x.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xbm.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xbm.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xc.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xc.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xcf.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xcf.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xpm.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xpm.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xps.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xps.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xtrn.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xtrn.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xwd.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/xwd.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ycbcr.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/ycbcr.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/yuv.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/coders/yuv.so
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/filters/analyze.la
/usr/lib64/ImageMagick-7.0.8/modules-Q16HDRI/filters/analyze.so
/usr/lib64/libMagick++-7.Q16HDRI.la
/usr/lib64/libMagick++-7.Q16HDRI.so
/usr/lib64/libMagick++-7.Q16HDRI.so.4
/usr/lib64/libMagick++-7.Q16HDRI.so.4.0.0
/usr/lib64/libMagickCore-7.Q16HDRI.la
/usr/lib64/libMagickCore-7.Q16HDRI.so
/usr/lib64/libMagickCore-7.Q16HDRI.so.6
/usr/lib64/libMagickCore-7.Q16HDRI.so.6.0.0
/usr/lib64/libMagickWand-7.Q16HDRI.la
/usr/lib64/libMagickWand-7.Q16HDRI.so
/usr/lib64/libMagickWand-7.Q16HDRI.so.6
/usr/lib64/libMagickWand-7.Q16HDRI.so.6.0.0
/usr/lib64/pkgconfig/ImageMagick-7.Q16HDRI.pc
/usr/lib64/pkgconfig/ImageMagick.pc
/usr/lib64/pkgconfig/Magick++-7.Q16HDRI.pc
/usr/lib64/pkgconfig/Magick++.pc
/usr/lib64/pkgconfig/MagickCore-7.Q16HDRI.pc
/usr/lib64/pkgconfig/MagickCore.pc
/usr/lib64/pkgconfig/MagickWand-7.Q16HDRI.pc
/usr/lib64/pkgconfig/MagickWand.pc
/usr/share/ImageMagick-7/english.xml
/usr/share/ImageMagick-7/francais.xml
/usr/share/ImageMagick-7/locale.xml
/usr/share/doc/ImageMagick-7/ChangeLog
/usr/share/doc/ImageMagick-7/LICENSE
/usr/share/doc/ImageMagick-7/NEWS.txt
/usr/share/doc/ImageMagick-7/images/ImageMagick.ico
/usr/share/doc/ImageMagick-7/images/affine.png
/usr/share/doc/ImageMagick-7/images/annotate.png
/usr/share/doc/ImageMagick-7/images/arc.png
/usr/share/doc/ImageMagick-7/images/atop.gif
/usr/share/doc/ImageMagick-7/images/background.jpg
/usr/share/doc/ImageMagick-7/images/black.png
/usr/share/doc/ImageMagick-7/images/bluebells_clipped.jpg
/usr/share/doc/ImageMagick-7/images/bluebells_darker.jpg
/usr/share/doc/ImageMagick-7/images/bluebells_lin.jpg
/usr/share/doc/ImageMagick-7/images/bluebells_log.jpg
/usr/share/doc/ImageMagick-7/images/button.gif
/usr/share/doc/ImageMagick-7/images/configure.jpg
/usr/share/doc/ImageMagick-7/images/cylinder_shaded.png
/usr/share/doc/ImageMagick-7/images/difference.png
/usr/share/doc/ImageMagick-7/images/examples.jpg
/usr/share/doc/ImageMagick-7/images/frame.jpg
/usr/share/doc/ImageMagick-7/images/fuzzy-magick.png
/usr/share/doc/ImageMagick-7/images/gaussian-blur.png
/usr/share/doc/ImageMagick-7/images/granite.png
/usr/share/doc/ImageMagick-7/images/imade_art2.jpg
/usr/share/doc/ImageMagick-7/images/label.gif
/usr/share/doc/ImageMagick-7/images/litecoin.png
/usr/share/doc/ImageMagick-7/images/logo-sm-flop.png
/usr/share/doc/ImageMagick-7/images/logo-sm-fx.png
/usr/share/doc/ImageMagick-7/images/logo-sm.png
/usr/share/doc/ImageMagick-7/images/logo.jpg
/usr/share/doc/ImageMagick-7/images/logo.png
/usr/share/doc/ImageMagick-7/images/montage.jpg
/usr/share/doc/ImageMagick-7/images/mountains-clahe.jpg
/usr/share/doc/ImageMagick-7/images/mountains-equalize.jpg
/usr/share/doc/ImageMagick-7/images/mountains.jpg
/usr/share/doc/ImageMagick-7/images/navy.png
/usr/share/doc/ImageMagick-7/images/objects.gif
/usr/share/doc/ImageMagick-7/images/objects.jpg
/usr/share/doc/ImageMagick-7/images/objects.png
/usr/share/doc/ImageMagick-7/images/over.gif
/usr/share/doc/ImageMagick-7/images/patterns/bricks.png
/usr/share/doc/ImageMagick-7/images/patterns/checkerboard.png
/usr/share/doc/ImageMagick-7/images/patterns/circles.png
/usr/share/doc/ImageMagick-7/images/patterns/crosshatch.png
/usr/share/doc/ImageMagick-7/images/patterns/crosshatch30.png
/usr/share/doc/ImageMagick-7/images/patterns/crosshatch45.png
/usr/share/doc/ImageMagick-7/images/patterns/fishscales.png
/usr/share/doc/ImageMagick-7/images/patterns/gray0.png
/usr/share/doc/ImageMagick-7/images/patterns/gray10.png
/usr/share/doc/ImageMagick-7/images/patterns/gray100.png
/usr/share/doc/ImageMagick-7/images/patterns/gray15.png
/usr/share/doc/ImageMagick-7/images/patterns/gray20.png
/usr/share/doc/ImageMagick-7/images/patterns/gray25.png
/usr/share/doc/ImageMagick-7/images/patterns/gray30.png
/usr/share/doc/ImageMagick-7/images/patterns/gray35.png
/usr/share/doc/ImageMagick-7/images/patterns/gray40.png
/usr/share/doc/ImageMagick-7/images/patterns/gray45.png
/usr/share/doc/ImageMagick-7/images/patterns/gray5.png
/usr/share/doc/ImageMagick-7/images/patterns/gray50.png
/usr/share/doc/ImageMagick-7/images/patterns/gray55.png
/usr/share/doc/ImageMagick-7/images/patterns/gray60.png
/usr/share/doc/ImageMagick-7/images/patterns/gray65.png
/usr/share/doc/ImageMagick-7/images/patterns/gray70.png
/usr/share/doc/ImageMagick-7/images/patterns/gray75.png
/usr/share/doc/ImageMagick-7/images/patterns/gray80.png
/usr/share/doc/ImageMagick-7/images/patterns/gray85.png
/usr/share/doc/ImageMagick-7/images/patterns/gray90.png
/usr/share/doc/ImageMagick-7/images/patterns/gray95.png
/usr/share/doc/ImageMagick-7/images/patterns/hexagons.png
/usr/share/doc/ImageMagick-7/images/patterns/horizontal.png
/usr/share/doc/ImageMagick-7/images/patterns/horizontal2.png
/usr/share/doc/ImageMagick-7/images/patterns/horizontal3.png
/usr/share/doc/ImageMagick-7/images/patterns/horizontalsaw.png
/usr/share/doc/ImageMagick-7/images/patterns/hs_bdiagonal.png
/usr/share/doc/ImageMagick-7/images/patterns/hs_cross.png
/usr/share/doc/ImageMagick-7/images/patterns/hs_diagcross.png
/usr/share/doc/ImageMagick-7/images/patterns/hs_fdiagonal.png
/usr/share/doc/ImageMagick-7/images/patterns/hs_horizontal.png
/usr/share/doc/ImageMagick-7/images/patterns/hs_vertical.png
/usr/share/doc/ImageMagick-7/images/patterns/left30.png
/usr/share/doc/ImageMagick-7/images/patterns/left45.png
/usr/share/doc/ImageMagick-7/images/patterns/leftshingle.png
/usr/share/doc/ImageMagick-7/images/patterns/octagons.png
/usr/share/doc/ImageMagick-7/images/patterns/right30.png
/usr/share/doc/ImageMagick-7/images/patterns/right45.png
/usr/share/doc/ImageMagick-7/images/patterns/rightshingle.png
/usr/share/doc/ImageMagick-7/images/patterns/smallfishscales.png
/usr/share/doc/ImageMagick-7/images/patterns/vertical.png
/usr/share/doc/ImageMagick-7/images/patterns/vertical2.png
/usr/share/doc/ImageMagick-7/images/patterns/vertical3.png
/usr/share/doc/ImageMagick-7/images/patterns/verticalbricks.png
/usr/share/doc/ImageMagick-7/images/patterns/verticalleftshingle.png
/usr/share/doc/ImageMagick-7/images/patterns/verticalrightshingle.png
/usr/share/doc/ImageMagick-7/images/patterns/verticalsaw.png
/usr/share/doc/ImageMagick-7/images/piechart.png
/usr/share/doc/ImageMagick-7/images/radial-gradient.png
/usr/share/doc/ImageMagick-7/images/reconstruct.jpg
/usr/share/doc/ImageMagick-7/images/red-ball.png
/usr/share/doc/ImageMagick-7/images/red-circle.png
/usr/share/doc/ImageMagick-7/images/right.gif
/usr/share/doc/ImageMagick-7/images/rose-over.png
/usr/share/doc/ImageMagick-7/images/rose-sigmoidal.png
/usr/share/doc/ImageMagick-7/images/rose.jpg
/usr/share/doc/ImageMagick-7/images/rose.png
/usr/share/doc/ImageMagick-7/images/rose.pnm
/usr/share/doc/ImageMagick-7/images/script.png
/usr/share/doc/ImageMagick-7/images/smile.gif
/usr/share/doc/ImageMagick-7/images/sponsor.jpg
/usr/share/doc/ImageMagick-7/images/sprite.jpg
/usr/share/doc/ImageMagick-7/images/t-shirt.png
/usr/share/doc/ImageMagick-7/images/wand.ico
/usr/share/doc/ImageMagick-7/images/wand.png
/usr/share/doc/ImageMagick-7/images/white-highlight.png
/usr/share/doc/ImageMagick-7/images/wizard.jpg
/usr/share/doc/ImageMagick-7/images/wizard.png
/usr/share/doc/ImageMagick-7/index.html
/usr/share/doc/ImageMagick-7/www/ImageMagickObject.html
/usr/share/doc/ImageMagick-7/www/Magick++/Blob.html
/usr/share/doc/ImageMagick-7/www/Magick++/Cache.fig
/usr/share/doc/ImageMagick-7/www/Magick++/Cache.png
/usr/share/doc/ImageMagick-7/www/Magick++/Cache.svg
/usr/share/doc/ImageMagick-7/www/Magick++/ChangeLog.html
/usr/share/doc/ImageMagick-7/www/Magick++/CoderInfo.html
/usr/share/doc/ImageMagick-7/www/Magick++/Color.html
/usr/share/doc/ImageMagick-7/www/Magick++/Documentation.html
/usr/share/doc/ImageMagick-7/www/Magick++/Drawable.html
/usr/share/doc/ImageMagick-7/www/Magick++/Drawable_example_1.png
/usr/share/doc/ImageMagick-7/www/Magick++/Enumerations.html
/usr/share/doc/ImageMagick-7/www/Magick++/Exception.html
/usr/share/doc/ImageMagick-7/www/Magick++/FormatCharacters.html
/usr/share/doc/ImageMagick-7/www/Magick++/Future.html
/usr/share/doc/ImageMagick-7/www/Magick++/Geometry.html
/usr/share/doc/ImageMagick-7/www/Magick++/Image++.html
/usr/share/doc/ImageMagick-7/www/Magick++/Image.fig
/usr/share/doc/ImageMagick-7/www/Magick++/Image.html
/usr/share/doc/ImageMagick-7/www/Magick++/Image.png
/usr/share/doc/ImageMagick-7/www/Magick++/ImageDesign.html
/usr/share/doc/ImageMagick-7/www/Magick++/ImageMagick.png
/usr/share/doc/ImageMagick-7/www/Magick++/Install.html
/usr/share/doc/ImageMagick-7/www/Magick++/Magick++.png
/usr/share/doc/ImageMagick-7/www/Magick++/Montage.html
/usr/share/doc/ImageMagick-7/www/Magick++/NEWS.html
/usr/share/doc/ImageMagick-7/www/Magick++/PixelPacket.html
/usr/share/doc/ImageMagick-7/www/Magick++/Pixels.html
/usr/share/doc/ImageMagick-7/www/Magick++/Quantum.html
/usr/share/doc/ImageMagick-7/www/Magick++/README.txt
/usr/share/doc/ImageMagick-7/www/Magick++/STL.html
/usr/share/doc/ImageMagick-7/www/Magick++/TypeMetric.html
/usr/share/doc/ImageMagick-7/www/Magick++/index.html
/usr/share/doc/ImageMagick-7/www/Magick++/magick.css
/usr/share/doc/ImageMagick-7/www/Magick++/montage-sample-framed.jpg
/usr/share/doc/ImageMagick-7/www/Magick++/right_triangle.png
/usr/share/doc/ImageMagick-7/www/Magick++/thumbnail-anatomy-framed.fig
/usr/share/doc/ImageMagick-7/www/Magick++/thumbnail-anatomy-framed.jpg
/usr/share/doc/ImageMagick-7/www/Magick++/thumbnail-anatomy-plain.fig
/usr/share/doc/ImageMagick-7/www/Magick++/thumbnail-anatomy-plain.jpg
/usr/share/doc/ImageMagick-7/www/Magick++/thumbnail-sample-framed.jpg
/usr/share/doc/ImageMagick-7/www/Magick++/thumbnail-sample-plain.jpg
/usr/share/doc/ImageMagick-7/www/advanced-unix-installation.html
/usr/share/doc/ImageMagick-7/www/advanced-windows-installation.html
/usr/share/doc/ImageMagick-7/www/animate.html
/usr/share/doc/ImageMagick-7/www/api.html
/usr/share/doc/ImageMagick-7/www/api/Image++.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ImageMagick_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ImageMagick_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/MagickCore_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/MagickCore_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/PreRvIcccm_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/PreRvIcccm_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/PreRvIcccm_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/animate-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/animate-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/animate_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/animate_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/animate_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/annotate_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/annotate_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/annotate_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/annotated.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/api_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/api_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/artifact_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/artifact_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/artifact_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/blob-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/blob-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/blob_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/blob_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/blob_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache-view_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache-view_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache-view_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/cache_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/classes.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/client_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/client_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/client_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/coder_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/coder_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/coder_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/color-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/color-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/color_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/color_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/color_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/colorspace-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/colorspace-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/colorspace_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/colorspace_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/colorspace_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/compare_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/compare_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/compare_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/composite-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/composite-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/composite_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/composite_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/composite_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/compress_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/compress_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/compress_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/configure_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/configure_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/configure_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/constitute_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/constitute_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/constitute_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/decorate_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/decorate_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/decorate_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/delegate_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/delegate_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/delegate_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/deprecate_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/deprecate_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/deprecate_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/dir_b44b349db36f8365f5234e57d3038770.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/dirs.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/display-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/display-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/display_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/display_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/display_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/distort_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/distort_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/distort_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/doxygen.css
/usr/share/doc/ImageMagick-7/www/api/MagickCore/doxygen.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/draw-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/draw-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/draw_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/draw_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/draw_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/effect_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/effect_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/effect_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/enhance_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/enhance_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/enhance_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/exception-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/exception-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/exception_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/exception_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/exception_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/files.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2blank.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2doc.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2folderclosed.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2folderopen.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2lastnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2link.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2mlastnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2mnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2node.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2plastnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2pnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/ftv2vertline.png
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x61.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x62.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x65.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x66.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x68.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x6b.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x6c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x6f.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x71.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x74.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x75.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x76.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x77.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x78.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x79.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_0x7a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_func.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x61.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x62.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x65.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x66.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x68.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x6b.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x6c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x6f.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x71.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x74.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x75.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x76.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x77.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x78.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x79.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/functions_vars_0x7a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/fx-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/fx-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/fx_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/fx_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/fx_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/gem_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/gem_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/gem_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/geometry_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/geometry_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/geometry_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x61.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x62.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x65.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x66.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x68.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x6a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x6b.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x6c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x6f.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x71.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x74.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x75.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x76.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x77.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x78.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x79.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_0x7a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x61.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x62.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x65.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x66.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x68.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x6b.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x6c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x6f.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x71.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x74.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x75.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x76.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x77.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x78.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_defs_0x79.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_enum.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x62.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x65.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x66.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x68.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x6a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x6b.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x6c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x6f.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x71.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x74.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x75.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x76.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x77.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x78.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x79.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_eval_0x7a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x62.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x65.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x66.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x68.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x6a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x6b.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x6c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x6f.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x71.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x74.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x75.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x76.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x77.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x78.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x79.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_func_0x7a.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_type.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/globals_vars.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/hashmap_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/hashmap_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/hashmap_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/identify_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/identify_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/identify_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/image-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/image-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/image_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/image_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/image_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/index.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/layer_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/layer_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/layer_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/list_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/list_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/list_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/locale_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/locale___8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/locale___8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/log_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/log_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/log_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mac_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mac_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mac_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magic_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magic_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magic_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magick-config_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magick-config_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magick-type_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magick-type_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magick_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magick_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/magick_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/main.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/matrix_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/matrix_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/matrix_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/memory_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/memory___8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/memory___8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/methods_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/methods_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mime-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mime-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mime_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mime_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/mime_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/module_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/module_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/module_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/monitor_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/monitor_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/monitor_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/montage_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/montage_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/montage_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/nt-base_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/nt-base_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/nt-base_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/nt-feature_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/nt-feature_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/nt-feature_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/option_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/option_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/option_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/paint_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/paint_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/paint_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/pixel-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/pixel-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/pixel_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/pixel_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/pixel_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/prepress_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/prepress_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/prepress_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/profile_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/profile_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/profile_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/property_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/property_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/property_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantize_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantize_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantize_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantum-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantum-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantum_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantum_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/quantum_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/random_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/random___8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/random___8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/registry_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/registry_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/registry_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resample_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resample_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resample_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resize-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resize-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resize_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resize_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resize_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resource_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resource___8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/resource___8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/segment_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/segment_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/segment_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/semaphore_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/semaphore_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/semaphore_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/shear_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/shear_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/shear_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/signature_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/signature_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/signature_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/splay-tree_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/splay-tree_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/splay-tree_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/static_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/static_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/static_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/statistic_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/statistic_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/statistic_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/stream-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/stream-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/stream_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/stream_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/stream_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/string_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/string___8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/string___8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/structHuffmanTable.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/structSemaphoreInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__AffineMatrix.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__Ascii85Info.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__BlobInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__CacheInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__CacheMethods.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__CacheView.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ChannelStatistics.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ChromaticityInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__Cluster.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__CoderInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ColorInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ColorPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ConfigureInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ContributionInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__CubeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__DIR.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__DataSegmentInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__DelegateInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__DiversityPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__DoublePixelPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__DrawInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__EdgeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ElementInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ElementReference.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__EntryInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ErrorInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__EventInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ExceptionInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ExtentPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__FrameInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__FxInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__GeometryInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__GhostscriptVectors.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__GradientInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__HandlerInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__HashmapInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__Image.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ImageAttribute.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ImageInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__IntervalTree.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__LinkedListInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__LocaleInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__LogInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__LongPixelPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MagicInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MagickInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MagickPixelPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MedianListNode.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MedianPixelList.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MedianSkipList.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MemoryInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MimeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ModuleInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__MontageInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__NTMEMORYSTATUSEX.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__NexusInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__NodeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__Nodes.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__OptionInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__PathInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__PixelPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__PointInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__PolygonInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__PrimaryInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__PrimitiveInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ProfileInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__QuantizeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__QuantumInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__QuantumState.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__RandomInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__RealPixelPacket.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__RectangleInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__RegistryInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ResampleFilter.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ResizeFilter.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ResourceInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__SegmentInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__SignatureInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__SplayTreeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__StopInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__StreamInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__StringInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ThresholdMap.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__Timer.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__TimerInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__TokenInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__TypeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__TypeMetric.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ViewInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__XImportInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__XMLTreeInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__XMLTreeRoot.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__XWidgetInfo.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ZeroCrossing.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__dirdesc.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/struct__ile3.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/structdirent.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/studio_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/studio_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/tab_b.gif
/usr/share/doc/ImageMagick-7/www/api/MagickCore/tab_l.gif
/usr/share/doc/ImageMagick-7/www/api/MagickCore/tab_r.gif
/usr/share/doc/ImageMagick-7/www/api/MagickCore/tabs.css
/usr/share/doc/ImageMagick-7/www/api/MagickCore/threshold_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/threshold_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/threshold_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/timer_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/timer_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/timer_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/token_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/token_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/token_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/transform_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/transform_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/transform_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/tree.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/type_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/type_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/type_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/utility_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/utility_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/utility_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/version_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/version_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/version_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/vms_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/vms_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/vms_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/widget_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/widget_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/widget_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xml-tree_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xml-tree_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xml-tree_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xwindow-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xwindow-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xwindow_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xwindow_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickCore/xwindow_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/MagickWand_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/MagickWand_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/animate_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/animate_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/animate_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/annotated.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/classes.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/compare_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/compare_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/compare_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/composite_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/composite_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/composite_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/conjure_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/conjure_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/conjure_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/convert_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/convert_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/convert_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/deprecate_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/deprecate_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/deprecate_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/dir_101f7ac0a894e32543a314e85b2e1524.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/dirs.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/display_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/display_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/display_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/doxygen.css
/usr/share/doc/ImageMagick-7/www/api/MagickWand/doxygen.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/drawing-wand_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/drawing-wand_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/drawing-wand_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/drawtest_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/files.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2blank.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2doc.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2folderclosed.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2folderopen.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2lastnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2link.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2mlastnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2mnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2node.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2plastnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2pnode.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/ftv2vertline.png
/usr/share/doc/ImageMagick-7/www/api/MagickWand/functions.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/functions_vars.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x61.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x62.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x65.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x6f.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x71.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x74.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x75.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x77.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_0x78.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_defs.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_enum.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_eval.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x63.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x64.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x67.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x69.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x6d.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x6e.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x70.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x72.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_func_0x73.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_type.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/globals_vars.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/identify_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/identify_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/identify_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/import_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/import_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/import_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/index.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-image_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-image_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-image_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-property_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-property_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-property_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-wand-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-wand-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-wand_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-wand_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick-wand_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick__wand_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/magick__wand_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/main.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/mogrify-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/mogrify-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/mogrify_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/mogrify_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/mogrify_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/montage_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/montage_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/montage_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-iterator_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-iterator_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-iterator_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-wand-private_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-wand-private_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-wand_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-wand_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/pixel-wand_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/stream_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/stream_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/stream_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/struct__CompositeOptions.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/struct__DrawVTable.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/struct__DrawingWand.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/struct__MagickWand.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/struct__PixelIterator.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/struct__PixelWand.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/studio_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/studio_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/tab_b.gif
/usr/share/doc/ImageMagick-7/www/api/MagickWand/tab_l.gif
/usr/share/doc/ImageMagick-7/www/api/MagickWand/tab_r.gif
/usr/share/doc/ImageMagick-7/www/api/MagickWand/tabs.css
/usr/share/doc/ImageMagick-7/www/api/MagickWand/tree.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/wand_8c.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/wand_8h-source.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/wand_8h.html
/usr/share/doc/ImageMagick-7/www/api/MagickWand/wandtest_8c.html
/usr/share/doc/ImageMagick-7/www/api/animate.html
/usr/share/doc/ImageMagick-7/www/api/annotate.html
/usr/share/doc/ImageMagick-7/www/api/attribute.html
/usr/share/doc/ImageMagick-7/www/api/blob.html
/usr/share/doc/ImageMagick-7/www/api/cache-view.html
/usr/share/doc/ImageMagick-7/www/api/cache.html
/usr/share/doc/ImageMagick-7/www/api/channel.html
/usr/share/doc/ImageMagick-7/www/api/cipher.html
/usr/share/doc/ImageMagick-7/www/api/color.html
/usr/share/doc/ImageMagick-7/www/api/colormap.html
/usr/share/doc/ImageMagick-7/www/api/colorspace.html
/usr/share/doc/ImageMagick-7/www/api/compare.html
/usr/share/doc/ImageMagick-7/www/api/composite.html
/usr/share/doc/ImageMagick-7/www/api/constitute.html
/usr/share/doc/ImageMagick-7/www/api/decorate.html
/usr/share/doc/ImageMagick-7/www/api/deprecate.html
/usr/share/doc/ImageMagick-7/www/api/display.html
/usr/share/doc/ImageMagick-7/www/api/distort.html
/usr/share/doc/ImageMagick-7/www/api/draw.html
/usr/share/doc/ImageMagick-7/www/api/drawing-wand.html
/usr/share/doc/ImageMagick-7/www/api/effect.html
/usr/share/doc/ImageMagick-7/www/api/enhance.html
/usr/share/doc/ImageMagick-7/www/api/exception.html
/usr/share/doc/ImageMagick-7/www/api/feature.html
/usr/share/doc/ImageMagick-7/www/api/fourier.html
/usr/share/doc/ImageMagick-7/www/api/fx.html
/usr/share/doc/ImageMagick-7/www/api/histogram.html
/usr/share/doc/ImageMagick-7/www/api/image-view.html
/usr/share/doc/ImageMagick-7/www/api/image.html
/usr/share/doc/ImageMagick-7/www/api/layer.html
/usr/share/doc/ImageMagick-7/www/api/list.html
/usr/share/doc/ImageMagick-7/www/api/magick++-classes.html
/usr/share/doc/ImageMagick-7/www/api/magick-deprecate.html
/usr/share/doc/ImageMagick-7/www/api/magick-image.html
/usr/share/doc/ImageMagick-7/www/api/magick-property.html
/usr/share/doc/ImageMagick-7/www/api/magick-wand.html
/usr/share/doc/ImageMagick-7/www/api/magick.html
/usr/share/doc/ImageMagick-7/www/api/memory.html
/usr/share/doc/ImageMagick-7/www/api/mime.html
/usr/share/doc/ImageMagick-7/www/api/module.html
/usr/share/doc/ImageMagick-7/www/api/mogrify.html
/usr/share/doc/ImageMagick-7/www/api/monitor.html
/usr/share/doc/ImageMagick-7/www/api/montage.html
/usr/share/doc/ImageMagick-7/www/api/morphology.html
/usr/share/doc/ImageMagick-7/www/api/paint.html
/usr/share/doc/ImageMagick-7/www/api/pixel-iterator.html
/usr/share/doc/ImageMagick-7/www/api/pixel-wand.html
/usr/share/doc/ImageMagick-7/www/api/profile.html
/usr/share/doc/ImageMagick-7/www/api/property.html
/usr/share/doc/ImageMagick-7/www/api/quantize.html
/usr/share/doc/ImageMagick-7/www/api/registry.html
/usr/share/doc/ImageMagick-7/www/api/resize.html
/usr/share/doc/ImageMagick-7/www/api/resource.html
/usr/share/doc/ImageMagick-7/www/api/segment.html
/usr/share/doc/ImageMagick-7/www/api/shear.html
/usr/share/doc/ImageMagick-7/www/api/signature.html
/usr/share/doc/ImageMagick-7/www/api/statistic.html
/usr/share/doc/ImageMagick-7/www/api/stream.html
/usr/share/doc/ImageMagick-7/www/api/transform.html
/usr/share/doc/ImageMagick-7/www/api/version.html
/usr/share/doc/ImageMagick-7/www/api/wand-view.html
/usr/share/doc/ImageMagick-7/www/architecture.html
/usr/share/doc/ImageMagick-7/www/assets/magick.css
/usr/share/doc/ImageMagick-7/www/assets/magick.js
/usr/share/doc/ImageMagick-7/www/binary-releases.html
/usr/share/doc/ImageMagick-7/www/changelog.html
/usr/share/doc/ImageMagick-7/www/cipher.html
/usr/share/doc/ImageMagick-7/www/clahe.html
/usr/share/doc/ImageMagick-7/www/color-management.html
/usr/share/doc/ImageMagick-7/www/color.html
/usr/share/doc/ImageMagick-7/www/command-line-options.html
/usr/share/doc/ImageMagick-7/www/command-line-processing.html
/usr/share/doc/ImageMagick-7/www/command-line-tools.html
/usr/share/doc/ImageMagick-7/www/compare.html
/usr/share/doc/ImageMagick-7/www/compose.html
/usr/share/doc/ImageMagick-7/www/composite.html
/usr/share/doc/ImageMagick-7/www/conjure.html
/usr/share/doc/ImageMagick-7/www/connected-components.html
/usr/share/doc/ImageMagick-7/www/contact.html
/usr/share/doc/ImageMagick-7/www/convert.html
/usr/share/doc/ImageMagick-7/www/develop.html
/usr/share/doc/ImageMagick-7/www/display.html
/usr/share/doc/ImageMagick-7/www/distribute-pixel-cache.html
/usr/share/doc/ImageMagick-7/www/download.html
/usr/share/doc/ImageMagick-7/www/escape.html
/usr/share/doc/ImageMagick-7/www/examples.html
/usr/share/doc/ImageMagick-7/www/exception.html
/usr/share/doc/ImageMagick-7/www/export.html
/usr/share/doc/ImageMagick-7/www/favicon.ico
/usr/share/doc/ImageMagick-7/www/formats.html
/usr/share/doc/ImageMagick-7/www/fx.html
/usr/share/doc/ImageMagick-7/www/gradient.html
/usr/share/doc/ImageMagick-7/www/high-dynamic-range.html
/usr/share/doc/ImageMagick-7/www/history.html
/usr/share/doc/ImageMagick-7/www/identify.html
/usr/share/doc/ImageMagick-7/www/import.html
/usr/share/doc/ImageMagick-7/www/index.html
/usr/share/doc/ImageMagick-7/www/install-source.html
/usr/share/doc/ImageMagick-7/www/jp2.html
/usr/share/doc/ImageMagick-7/www/license.html
/usr/share/doc/ImageMagick-7/www/links.html
/usr/share/doc/ImageMagick-7/www/magick++.html
/usr/share/doc/ImageMagick-7/www/magick-core.html
/usr/share/doc/ImageMagick-7/www/magick-script.html
/usr/share/doc/ImageMagick-7/www/magick-vector-graphics.html
/usr/share/doc/ImageMagick-7/www/magick-wand.html
/usr/share/doc/ImageMagick-7/www/magick.html
/usr/share/doc/ImageMagick-7/www/miff.html
/usr/share/doc/ImageMagick-7/www/mirror.html
/usr/share/doc/ImageMagick-7/www/mogrify.html
/usr/share/doc/ImageMagick-7/www/montage.html
/usr/share/doc/ImageMagick-7/www/motion-picture.html
/usr/share/doc/ImageMagick-7/www/opencl.html
/usr/share/doc/ImageMagick-7/www/openmp.html
/usr/share/doc/ImageMagick-7/www/perl-magick.html
/usr/share/doc/ImageMagick-7/www/porting.html
/usr/share/doc/ImageMagick-7/www/quantize.html
/usr/share/doc/ImageMagick-7/www/resources.html
/usr/share/doc/ImageMagick-7/www/search.html
/usr/share/doc/ImageMagick-7/www/security-policy.html
/usr/share/doc/ImageMagick-7/www/sitemap.html
/usr/share/doc/ImageMagick-7/www/source/analyze.c
/usr/share/doc/ImageMagick-7/www/source/coder.xml
/usr/share/doc/ImageMagick-7/www/source/colors.xml
/usr/share/doc/ImageMagick-7/www/source/configure.xml
/usr/share/doc/ImageMagick-7/www/source/contrast.c
/usr/share/doc/ImageMagick-7/www/source/core.c
/usr/share/doc/ImageMagick-7/www/source/delegates.xml
/usr/share/doc/ImageMagick-7/www/source/english.xml
/usr/share/doc/ImageMagick-7/www/source/examples.pl
/usr/share/doc/ImageMagick-7/www/source/francais.xml
/usr/share/doc/ImageMagick-7/www/source/incantation.msl
/usr/share/doc/ImageMagick-7/www/source/locale.xml
/usr/share/doc/ImageMagick-7/www/source/log.xml
/usr/share/doc/ImageMagick-7/www/source/magic.xml
/usr/share/doc/ImageMagick-7/www/source/mgk.c
/usr/share/doc/ImageMagick-7/www/source/mime.xml
/usr/share/doc/ImageMagick-7/www/source/piechart.mvg
/usr/share/doc/ImageMagick-7/www/source/piechart.svg
/usr/share/doc/ImageMagick-7/www/source/policy.xml
/usr/share/doc/ImageMagick-7/www/source/quantization-table.xml
/usr/share/doc/ImageMagick-7/www/source/thresholds.xml
/usr/share/doc/ImageMagick-7/www/source/type-apple.xml
/usr/share/doc/ImageMagick-7/www/source/type-dejavu.xml
/usr/share/doc/ImageMagick-7/www/source/type-ghostscript.xml
/usr/share/doc/ImageMagick-7/www/source/type-urw-base35.xml
/usr/share/doc/ImageMagick-7/www/source/type-windows.xml
/usr/share/doc/ImageMagick-7/www/source/type.xml
/usr/share/doc/ImageMagick-7/www/source/wand.c
/usr/share/doc/ImageMagick-7/www/stream.html
/usr/share/doc/ImageMagick-7/www/support.html
/usr/share/doc/ImageMagick-7/www/wand.png
/usr/share/doc/ImageMagick-7/www/webp.html
/usr/share/man/man1/ImageMagick.1.gz
/usr/share/man/man1/Magick++-config.1.gz
/usr/share/man/man1/MagickCore-config.1.gz
/usr/share/man/man1/MagickWand-config.1.gz
/usr/share/man/man1/animate.1.gz
/usr/share/man/man1/compare.1.gz
/usr/share/man/man1/composite.1.gz
/usr/share/man/man1/conjure.1.gz
/usr/share/man/man1/convert.1.gz
/usr/share/man/man1/display.1.gz
/usr/share/man/man1/identify.1.gz
/usr/share/man/man1/import.1.gz
/usr/share/man/man1/magick-script.1.gz
/usr/share/man/man1/magick.1.gz
/usr/share/man/man1/mogrify.1.gz
/usr/share/man/man1/montage.1.gz
/usr/share/man/man1/stream.1.gz
/usr/share/man/man3/Image::Magick.3.gz
/usr/share/man/man3/Image::Magick::Q16HDRI.3.gz


%changelog
# let's skip this for now

