Name:       gcr
Version:    3.28.1
Release:    1
Summary:    TODO
License:    GPL3
Prefix:     /usr
Source0:    %{name}-%{version}.tar.xz

%description
TODO

%prep
%setup -a 0

%build
sed -i -r 's:"(/desktop):"/org/gnome\1:' schema/*.xml &&
%configure
%make_build

%install    
rm -rf %{buildroot}
make install DESTDIR=%{buildroot}
rm -vf %{buildroot}%{_infodir}/dir

%files
/usr/bin/gcr-viewer
/usr/include/gck-1/gck/gck-deprecated.h
/usr/include/gck-1/gck/gck-enum-types.h
/usr/include/gck-1/gck/gck-version.h
/usr/include/gck-1/gck/gck.h
/usr/include/gck-1/gck/pkcs11.h
/usr/include/gck-1/gck/pkcs11n.h
/usr/include/gck-1/gck/pkcs11x.h
/usr/include/gcr-3/gcr/gcr-base.h
/usr/include/gcr-3/gcr/gcr-certificate-chain.h
/usr/include/gcr-3/gcr/gcr-certificate-request.h
/usr/include/gcr-3/gcr/gcr-certificate.h
/usr/include/gcr-3/gcr/gcr-collection.h
/usr/include/gcr-3/gcr/gcr-column.h
/usr/include/gcr-3/gcr/gcr-comparable.h
/usr/include/gcr-3/gcr/gcr-deprecated-base.h
/usr/include/gcr-3/gcr/gcr-enum-types-base.h
/usr/include/gcr-3/gcr/gcr-filter-collection.h
/usr/include/gcr-3/gcr/gcr-fingerprint.h
/usr/include/gcr-3/gcr/gcr-icons.h
/usr/include/gcr-3/gcr/gcr-import-interaction.h
/usr/include/gcr-3/gcr/gcr-importer.h
/usr/include/gcr-3/gcr/gcr-library.h
/usr/include/gcr-3/gcr/gcr-mock-prompter.h
/usr/include/gcr-3/gcr/gcr-parser.h
/usr/include/gcr-3/gcr/gcr-pkcs11-certificate.h
/usr/include/gcr-3/gcr/gcr-prompt.h
/usr/include/gcr-3/gcr/gcr-secret-exchange.h
/usr/include/gcr-3/gcr/gcr-secure-memory.h
/usr/include/gcr-3/gcr/gcr-simple-certificate.h
/usr/include/gcr-3/gcr/gcr-simple-collection.h
/usr/include/gcr-3/gcr/gcr-ssh-askpass.h
/usr/include/gcr-3/gcr/gcr-system-prompt.h
/usr/include/gcr-3/gcr/gcr-system-prompter.h
/usr/include/gcr-3/gcr/gcr-trust.h
/usr/include/gcr-3/gcr/gcr-types.h
/usr/include/gcr-3/gcr/gcr-union-collection.h
/usr/include/gcr-3/gcr/gcr-unlock-options.h
/usr/include/gcr-3/gcr/gcr-version.h
/usr/include/gcr-3/gcr/gcr.h
/usr/include/gcr-3/ui/gcr-certificate-basics-widget.h
/usr/include/gcr-3/ui/gcr-certificate-details-widget.h
/usr/include/gcr-3/ui/gcr-certificate-renderer.h
/usr/include/gcr-3/ui/gcr-certificate-widget.h
/usr/include/gcr-3/ui/gcr-collection-model.h
/usr/include/gcr-3/ui/gcr-combo-selector.h
/usr/include/gcr-3/ui/gcr-deprecated.h
/usr/include/gcr-3/ui/gcr-enum-types.h
/usr/include/gcr-3/ui/gcr-failure-renderer.h
/usr/include/gcr-3/ui/gcr-import-button.h
/usr/include/gcr-3/ui/gcr-key-renderer.h
/usr/include/gcr-3/ui/gcr-key-widget.h
/usr/include/gcr-3/ui/gcr-list-selector.h
/usr/include/gcr-3/ui/gcr-prompt-dialog.h
/usr/include/gcr-3/ui/gcr-renderer.h
/usr/include/gcr-3/ui/gcr-secure-entry-buffer.h
/usr/include/gcr-3/ui/gcr-tree-selector.h
/usr/include/gcr-3/ui/gcr-ui.h
/usr/include/gcr-3/ui/gcr-unlock-options-widget.h
/usr/include/gcr-3/ui/gcr-viewer-widget.h
/usr/include/gcr-3/ui/gcr-viewer.h
/usr/lib64/girepository-1.0/Gck-1.typelib
/usr/lib64/girepository-1.0/Gcr-3.typelib
/usr/lib64/girepository-1.0/GcrUi-3.typelib
/usr/lib64/libgck-1.la
/usr/lib64/libgck-1.so
/usr/lib64/libgck-1.so.0
/usr/lib64/libgck-1.so.0.0.0
/usr/lib64/libgcr-3.so
/usr/lib64/libgcr-3.so.1
/usr/lib64/libgcr-3.so.1.0.0
/usr/lib64/libgcr-base-3.la
/usr/lib64/libgcr-base-3.so
/usr/lib64/libgcr-base-3.so.1
/usr/lib64/libgcr-base-3.so.1.0.0
/usr/lib64/libgcr-ui-3.la
/usr/lib64/libgcr-ui-3.so
/usr/lib64/libgcr-ui-3.so.1
/usr/lib64/libgcr-ui-3.so.1.0.0
/usr/lib64/pkgconfig/gck-1.pc
/usr/lib64/pkgconfig/gcr-3.pc
/usr/lib64/pkgconfig/gcr-base-3.pc
/usr/lib64/pkgconfig/gcr-ui-3.pc
/usr/libexec/gcr-prompter
/usr/libexec/gcr-ssh-askpass
/usr/share/GConf/gsettings/org.gnome.crypto.pgp.convert
/usr/share/GConf/gsettings/org.gnome.crypto.pgp_keyservers.convert
/usr/share/applications/gcr-prompter.desktop
/usr/share/applications/gcr-viewer.desktop
/usr/share/dbus-1/services/org.gnome.keyring.PrivatePrompter.service
/usr/share/dbus-1/services/org.gnome.keyring.SystemPrompter.service
/usr/share/gir-1.0/Gck-1.gir
/usr/share/gir-1.0/Gcr-3.gir
/usr/share/gir-1.0/GcrUi-3.gir
/usr/share/glib-2.0/schemas/org.gnome.crypto.pgp.gschema.xml
/usr/share/gtk-doc/html/gck/GckAttributes.html
/usr/share/gtk-doc/html/gck/GckEnumerator.html
/usr/share/gtk-doc/html/gck/GckModule.html
/usr/share/gtk-doc/html/gck/GckObject.html
/usr/share/gtk-doc/html/gck/GckObjectCache.html
/usr/share/gtk-doc/html/gck/GckSession.html
/usr/share/gtk-doc/html/gck/GckSlot.html
/usr/share/gtk-doc/html/gck/annotation-glossary.html
/usr/share/gtk-doc/html/gck/gck-Errors.html
/usr/share/gtk-doc/html/gck/gck-GckAttribute.html
/usr/share/gtk-doc/html/gck/gck-GckModule-lists.html
/usr/share/gtk-doc/html/gck/gck-Library-Utilities.html
/usr/share/gtk-doc/html/gck/gck-Miscellaneous-Functions.html
/usr/share/gtk-doc/html/gck/gck-PKCS11-URIs.html
/usr/share/gtk-doc/html/gck/gck.devhelp2
/usr/share/gtk-doc/html/gck/home.png
/usr/share/gtk-doc/html/gck/index.html
/usr/share/gtk-doc/html/gck/left-insensitive.png
/usr/share/gtk-doc/html/gck/left.png
/usr/share/gtk-doc/html/gck/pkcs11-links.html
/usr/share/gtk-doc/html/gck/reference.html
/usr/share/gtk-doc/html/gck/right-insensitive.png
/usr/share/gtk-doc/html/gck/right.png
/usr/share/gtk-doc/html/gck/style.css
/usr/share/gtk-doc/html/gck/up-insensitive.png
/usr/share/gtk-doc/html/gck/up.png
/usr/share/gtk-doc/html/gcr-3/GcrCertificate.html
/usr/share/gtk-doc/html/gcr-3/GcrCertificateChain.html
/usr/share/gtk-doc/html/gcr-3/GcrCertificateWidget.html
/usr/share/gtk-doc/html/gcr-3/GcrCollection.html
/usr/share/gtk-doc/html/gcr-3/GcrCollectionModel.html
/usr/share/gtk-doc/html/gcr-3/GcrComboSelector.html
/usr/share/gtk-doc/html/gcr-3/GcrComparable.html
/usr/share/gtk-doc/html/gcr-3/GcrImportButton.html
/usr/share/gtk-doc/html/gcr-3/GcrImporter.html
/usr/share/gtk-doc/html/gcr-3/GcrKeyWidget.html
/usr/share/gtk-doc/html/gcr-3/GcrListSelector.html
/usr/share/gtk-doc/html/gcr-3/GcrParser.html
/usr/share/gtk-doc/html/gcr-3/GcrPkcs11Certificate.html
/usr/share/gtk-doc/html/gcr-3/GcrPrompt.html
/usr/share/gtk-doc/html/gcr-3/GcrPromptDialog.html
/usr/share/gtk-doc/html/gcr-3/GcrRenderer.html
/usr/share/gtk-doc/html/gcr-3/GcrSecretExchange.html
/usr/share/gtk-doc/html/gcr-3/GcrSecureEntryBuffer.html
/usr/share/gtk-doc/html/gcr-3/GcrSimpleCertificate.html
/usr/share/gtk-doc/html/gcr-3/GcrSimpleCollection.html
/usr/share/gtk-doc/html/gcr-3/GcrSystemPrompt.html
/usr/share/gtk-doc/html/gcr-3/GcrSystemPrompter.html
/usr/share/gtk-doc/html/gcr-3/GcrTreeSelector.html
/usr/share/gtk-doc/html/gcr-3/GcrViewer.html
/usr/share/gtk-doc/html/gcr-3/GcrViewerWidget.html
/usr/share/gtk-doc/html/gcr-3/annotation-glossary.html
/usr/share/gtk-doc/html/gcr-3/certificate-widget.png
/usr/share/gtk-doc/html/gcr-3/certificates.html
/usr/share/gtk-doc/html/gcr-3/ch01.html
/usr/share/gtk-doc/html/gcr-3/collections.html
/usr/share/gtk-doc/html/gcr-3/combo-selector.png
/usr/share/gtk-doc/html/gcr-3/gcr-3.devhelp2
/usr/share/gtk-doc/html/gcr-3/gcr-GcrCertificateRequest.html
/usr/share/gtk-doc/html/gcr-3/gcr-GcrColumn.html
/usr/share/gtk-doc/html/gcr-3/gcr-GcrImportInteraction.html
/usr/share/gtk-doc/html/gcr-3/gcr-GcrSshAskpass.html
/usr/share/gtk-doc/html/gcr-3/gcr-Key-Fingerprints.html
/usr/share/gtk-doc/html/gcr-3/gcr-Library-PKCS#11.html
/usr/share/gtk-doc/html/gcr-3/gcr-Library-Utilities.html
/usr/share/gtk-doc/html/gcr-3/gcr-Non-pageable-Memory.html
/usr/share/gtk-doc/html/gcr-3/gcr-Trust-Storage-and-Lookups.html
/usr/share/gtk-doc/html/gcr-3/home.png
/usr/share/gtk-doc/html/gcr-3/import-button.png
/usr/share/gtk-doc/html/gcr-3/index.html
/usr/share/gtk-doc/html/gcr-3/key-widget.png
/usr/share/gtk-doc/html/gcr-3/left-insensitive.png
/usr/share/gtk-doc/html/gcr-3/left.png
/usr/share/gtk-doc/html/gcr-3/list-selector.png
/usr/share/gtk-doc/html/gcr-3/misc.html
/usr/share/gtk-doc/html/gcr-3/prompts.html
/usr/share/gtk-doc/html/gcr-3/right-insensitive.png
/usr/share/gtk-doc/html/gcr-3/right.png
/usr/share/gtk-doc/html/gcr-3/storage.html
/usr/share/gtk-doc/html/gcr-3/style.css
/usr/share/gtk-doc/html/gcr-3/tree-selector.png
/usr/share/gtk-doc/html/gcr-3/up-insensitive.png
/usr/share/gtk-doc/html/gcr-3/up.png
/usr/share/gtk-doc/html/gcr-3/viewer-widget.png
/usr/share/gtk-doc/html/gcr-3/widgets.html
/usr/share/icons/hicolor/16x16/apps/gcr-gnupg.png
/usr/share/icons/hicolor/16x16/apps/gcr-key-pair.png
/usr/share/icons/hicolor/16x16/apps/gcr-key.png
/usr/share/icons/hicolor/16x16/apps/gcr-password.png
/usr/share/icons/hicolor/16x16/apps/gcr-smart-card.png
/usr/share/icons/hicolor/22x22/apps/gcr-gnupg.png
/usr/share/icons/hicolor/22x22/apps/gcr-key-pair.png
/usr/share/icons/hicolor/22x22/apps/gcr-key.png
/usr/share/icons/hicolor/22x22/apps/gcr-password.png
/usr/share/icons/hicolor/22x22/apps/gcr-smart-card.png
/usr/share/icons/hicolor/24x24/apps/gcr-gnupg.png
/usr/share/icons/hicolor/24x24/apps/gcr-key-pair.png
/usr/share/icons/hicolor/24x24/apps/gcr-key.png
/usr/share/icons/hicolor/24x24/apps/gcr-password.png
/usr/share/icons/hicolor/24x24/apps/gcr-smart-card.png
/usr/share/icons/hicolor/256x256/apps/gcr-gnupg.png
/usr/share/icons/hicolor/256x256/apps/gcr-password.png
/usr/share/icons/hicolor/256x256/apps/gcr-smart-card.png
/usr/share/icons/hicolor/32x32/apps/gcr-gnupg.png
/usr/share/icons/hicolor/32x32/apps/gcr-key-pair.png
/usr/share/icons/hicolor/32x32/apps/gcr-key.png
/usr/share/icons/hicolor/32x32/apps/gcr-password.png
/usr/share/icons/hicolor/32x32/apps/gcr-smart-card.png
/usr/share/icons/hicolor/48x48/apps/gcr-gnupg.png
/usr/share/icons/hicolor/48x48/apps/gcr-key-pair.png
/usr/share/icons/hicolor/48x48/apps/gcr-key.png
/usr/share/icons/hicolor/48x48/apps/gcr-password.png
/usr/share/icons/hicolor/48x48/apps/gcr-smart-card.png
/usr/share/locale/af/LC_MESSAGES/gcr.mo
/usr/share/locale/ar/LC_MESSAGES/gcr.mo
/usr/share/locale/as/LC_MESSAGES/gcr.mo
/usr/share/locale/ast/LC_MESSAGES/gcr.mo
/usr/share/locale/az/LC_MESSAGES/gcr.mo
/usr/share/locale/be/LC_MESSAGES/gcr.mo
/usr/share/locale/be@latin/LC_MESSAGES/gcr.mo
/usr/share/locale/bg/LC_MESSAGES/gcr.mo
/usr/share/locale/bn/LC_MESSAGES/gcr.mo
/usr/share/locale/bn_IN/LC_MESSAGES/gcr.mo
/usr/share/locale/bs/LC_MESSAGES/gcr.mo
/usr/share/locale/ca/LC_MESSAGES/gcr.mo
/usr/share/locale/ca@valencia/LC_MESSAGES/gcr.mo
/usr/share/locale/cs/LC_MESSAGES/gcr.mo
/usr/share/locale/cy/LC_MESSAGES/gcr.mo
/usr/share/locale/da/LC_MESSAGES/gcr.mo
/usr/share/locale/de/LC_MESSAGES/gcr.mo
/usr/share/locale/dz/LC_MESSAGES/gcr.mo
/usr/share/locale/el/LC_MESSAGES/gcr.mo
/usr/share/locale/en@shaw/LC_MESSAGES/gcr.mo
/usr/share/locale/en_CA/LC_MESSAGES/gcr.mo
/usr/share/locale/en_GB/LC_MESSAGES/gcr.mo
/usr/share/locale/eo/LC_MESSAGES/gcr.mo
/usr/share/locale/es/LC_MESSAGES/gcr.mo
/usr/share/locale/et/LC_MESSAGES/gcr.mo
/usr/share/locale/eu/LC_MESSAGES/gcr.mo
/usr/share/locale/fa/LC_MESSAGES/gcr.mo
/usr/share/locale/fi/LC_MESSAGES/gcr.mo
/usr/share/locale/fr/LC_MESSAGES/gcr.mo
/usr/share/locale/fur/LC_MESSAGES/gcr.mo
/usr/share/locale/ga/LC_MESSAGES/gcr.mo
/usr/share/locale/gl/LC_MESSAGES/gcr.mo
/usr/share/locale/gu/LC_MESSAGES/gcr.mo
/usr/share/locale/he/LC_MESSAGES/gcr.mo
/usr/share/locale/hi/LC_MESSAGES/gcr.mo
/usr/share/locale/hr/LC_MESSAGES/gcr.mo
/usr/share/locale/hu/LC_MESSAGES/gcr.mo
/usr/share/locale/id/LC_MESSAGES/gcr.mo
/usr/share/locale/is/LC_MESSAGES/gcr.mo
/usr/share/locale/it/LC_MESSAGES/gcr.mo
/usr/share/locale/ja/LC_MESSAGES/gcr.mo
/usr/share/locale/ka/LC_MESSAGES/gcr.mo
/usr/share/locale/kk/LC_MESSAGES/gcr.mo
/usr/share/locale/kn/LC_MESSAGES/gcr.mo
/usr/share/locale/ko/LC_MESSAGES/gcr.mo
/usr/share/locale/lt/LC_MESSAGES/gcr.mo
/usr/share/locale/lv/LC_MESSAGES/gcr.mo
/usr/share/locale/mai/LC_MESSAGES/gcr.mo
/usr/share/locale/mg/LC_MESSAGES/gcr.mo
/usr/share/locale/mk/LC_MESSAGES/gcr.mo
/usr/share/locale/ml/LC_MESSAGES/gcr.mo
/usr/share/locale/mn/LC_MESSAGES/gcr.mo
/usr/share/locale/mr/LC_MESSAGES/gcr.mo
/usr/share/locale/ms/LC_MESSAGES/gcr.mo
/usr/share/locale/nb/LC_MESSAGES/gcr.mo
/usr/share/locale/ne/LC_MESSAGES/gcr.mo
/usr/share/locale/nl/LC_MESSAGES/gcr.mo
/usr/share/locale/nn/LC_MESSAGES/gcr.mo
/usr/share/locale/oc/LC_MESSAGES/gcr.mo
/usr/share/locale/or/LC_MESSAGES/gcr.mo
/usr/share/locale/pa/LC_MESSAGES/gcr.mo
/usr/share/locale/pl/LC_MESSAGES/gcr.mo
/usr/share/locale/pt/LC_MESSAGES/gcr.mo
/usr/share/locale/pt_BR/LC_MESSAGES/gcr.mo
/usr/share/locale/ro/LC_MESSAGES/gcr.mo
/usr/share/locale/ru/LC_MESSAGES/gcr.mo
/usr/share/locale/rw/LC_MESSAGES/gcr.mo
/usr/share/locale/si/LC_MESSAGES/gcr.mo
/usr/share/locale/sk/LC_MESSAGES/gcr.mo
/usr/share/locale/sl/LC_MESSAGES/gcr.mo
/usr/share/locale/sq/LC_MESSAGES/gcr.mo
/usr/share/locale/sr/LC_MESSAGES/gcr.mo
/usr/share/locale/sr@latin/LC_MESSAGES/gcr.mo
/usr/share/locale/sv/LC_MESSAGES/gcr.mo
/usr/share/locale/ta/LC_MESSAGES/gcr.mo
/usr/share/locale/te/LC_MESSAGES/gcr.mo
/usr/share/locale/tg/LC_MESSAGES/gcr.mo
/usr/share/locale/th/LC_MESSAGES/gcr.mo
/usr/share/locale/tr/LC_MESSAGES/gcr.mo
/usr/share/locale/ug/LC_MESSAGES/gcr.mo
/usr/share/locale/uk/LC_MESSAGES/gcr.mo
/usr/share/locale/vi/LC_MESSAGES/gcr.mo
/usr/share/locale/xh/LC_MESSAGES/gcr.mo
/usr/share/locale/zh_CN/LC_MESSAGES/gcr.mo
/usr/share/locale/zh_HK/LC_MESSAGES/gcr.mo
/usr/share/locale/zh_TW/LC_MESSAGES/gcr.mo
/usr/share/mime/packages/gcr-crypto-types.xml


%changelog
# let's skip this for now

